//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmpresaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmpresaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.EmpresaResource", typeof(EmpresaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código para o cadastramento da não foi devidamente informado..
        /// </summary>
        public static string Erro_CodigoVazioOuInvalido {
            get {
                return ResourceManager.GetString("Erro_CodigoVazioOuInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail não foi informado corretamente..
        /// </summary>
        public static string Erro_EmailVazioOuInvalido {
            get {
                return ResourceManager.GetString("Erro_EmailVazioOuInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereço não foi devidamente informado..
        /// </summary>
        public static string Erro_EnderecoVazioOuInvalido {
            get {
                return ResourceManager.GetString("Erro_EnderecoVazioOuInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome fantiasia informado está inválido.
        /// </summary>
        public static string Erro_NomeFantasiaVazioOuInvalido {
            get {
                return ResourceManager.GetString("Erro_NomeFantasiaVazioOuInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número não foi devidamente informado.
        /// </summary>
        public static string Erro_NumeroVazioOuInvalido {
            get {
                return ResourceManager.GetString("Erro_NumeroVazioOuInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status informado está inválido ou não condiz com o que há no sistema..
        /// </summary>
        public static string Erro_StatusInvalido {
            get {
                return ResourceManager.GetString("Erro_StatusInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do código é entre 3 até 25 caracteres..
        /// </summary>
        public static string Erro_TamanhoCodigo {
            get {
                return ResourceManager.GetString("Erro_TamanhoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do e-mail é entre 10 a 30 caracteres.
        /// </summary>
        public static string Erro_TamanhoEmail {
            get {
                return ResourceManager.GetString("Erro_TamanhoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho para endereço é entre 20 a 200 caracteres..
        /// </summary>
        public static string Erro_TamanhoEndereco {
            get {
                return ResourceManager.GetString("Erro_TamanhoEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do nome fantasia é entre 20 a 150 caracteres..
        /// </summary>
        public static string Erro_TamanhoNomeFantasia {
            get {
                return ResourceManager.GetString("Erro_TamanhoNomeFantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do número de telefone é de até 16 caracteres..
        /// </summary>
        public static string Erro_TamanhoNumero {
            get {
                return ResourceManager.GetString("Erro_TamanhoNumero", resourceCulture);
            }
        }
    }
}
