//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmpresaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmpresaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.EmpresaResource", typeof(EmpresaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to código.
        /// </summary>
        public static string Campo_Codigo {
            get {
                return ResourceManager.GetString("Campo_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string Campo_Email {
            get {
                return ResourceManager.GetString("Campo_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endereço.
        /// </summary>
        public static string Campo_Endereco {
            get {
                return ResourceManager.GetString("Campo_Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nome fantasia.
        /// </summary>
        public static string Campo_NomeFantasia {
            get {
                return ResourceManager.GetString("Campo_NomeFantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telefone.
        /// </summary>
        public static string Campo_Telefone {
            get {
                return ResourceManager.GetString("Campo_Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O vínculo ou a empresa não está ativo..
        /// </summary>
        public static string Erro_AcessoIndisponivel {
            get {
                return ResourceManager.GetString("Erro_AcessoIndisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cadastro da empresa já foi concluído ou possui vínculos..
        /// </summary>
        public static string Erro_CadastroConcluido {
            get {
                return ResourceManager.GetString("Erro_CadastroConcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter no máximo {1} caracteres..
        /// </summary>
        public static string Erro_CampoLongo {
            get {
                return ResourceManager.GetString("Erro_CampoLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string Erro_CampoObrigatorio {
            get {
                return ResourceManager.GetString("Erro_CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma empresa com o código informado..
        /// </summary>
        public static string Erro_CodigoExistente {
            get {
                return ResourceManager.GetString("Erro_CodigoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um e-mail válido para a empresa..
        /// </summary>
        public static string Erro_EmailInvalido {
            get {
                return ResourceManager.GetString("Erro_EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe os dados da empresa..
        /// </summary>
        public static string Erro_RegistroNulo {
            get {
                return ResourceManager.GetString("Erro_RegistroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O responsável deve possuir uma conta ativa com e-mail confirmado..
        /// </summary>
        public static string Erro_ResponsavelInvalido {
            get {
                return ResourceManager.GetString("Erro_ResponsavelInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário já possui vínculo com uma empresa..
        /// </summary>
        public static string Erro_UsuarioJaVinculado {
            get {
                return ResourceManager.GetString("Erro_UsuarioJaVinculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível identificar o usuário autenticado..
        /// </summary>
        public static string Erro_UsuarioNaoIdentificado {
            get {
                return ResourceManager.GetString("Erro_UsuarioNaoIdentificado", resourceCulture);
            }
        }
    }
}
