//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TarefaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TarefaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.TarefaResource", typeof(TarefaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova tarefa atribuída: {0}.
        /// </summary>
        public static string Assunto_EmailTarefaAtribuida {
            get {
                return ResourceManager.GetString("Assunto_EmailTarefaAtribuida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa criada, mas não foi possível enviar o e-mail de notificação..
        /// </summary>
        public static string Aviso_EmailNotificacaoNaoEnviado {
            get {
                return ResourceManager.GetString("Aviso_EmailNotificacaoNaoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cargo.
        /// </summary>
        public static string Campo_Cargo {
            get {
                return ResourceManager.GetString("Campo_Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        public static string Campo_Departamento {
            get {
                return ResourceManager.GetString("Campo_Departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino inicial da tarefa.
        /// </summary>
        public static string Campo_DestinoInicial {
            get {
                return ResourceManager.GetString("Campo_DestinoInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado da tarefa.
        /// </summary>
        public static string Campo_EstadoDaTarefa {
            get {
                return ResourceManager.GetString("Campo_EstadoDaTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        public static string Campo_Titulo {
            get {
                return ResourceManager.GetString("Campo_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Campo_Usuario {
            get {
                return ResourceManager.GetString("Campo_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao informado.
        /// </summary>
        public static string Descricao_EstadoNaoInformado {
            get {
                return ResourceManager.GetString("Descricao_EstadoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefas.
        /// </summary>
        public static string Descricao_ModuloTarefas {
            get {
                return ResourceManager.GetString("Descricao_ModuloTarefas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nao identificada.
        /// </summary>
        public static string Descricao_TarefaNaoIdentificada {
            get {
                return ResourceManager.GetString("Descricao_TarefaNaoIdentificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não possui acesso ao histórico desta tarefa..
        /// </summary>
        public static string Erro_AcessoHistoricoNaoPermitido {
            get {
                return ResourceManager.GetString("Erro_AcessoHistoricoNaoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum aprovador disponivel para esta solicitacao..
        /// </summary>
        public static string Erro_AprovadorIndisponivel {
            get {
                return ResourceManager.GetString("Erro_AprovadorIndisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao foi possivel criar a tarefa porque o usuario responsavel nao possui gestor imediato e o departamento nao possui gestor definido..
        /// </summary>
        public static string Erro_AprovadorObrigatorio {
            get {
                return ResourceManager.GetString("Erro_AprovadorObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao foi possivel assumir a tarefa..
        /// </summary>
        public static string Erro_AssumirTarefa {
            get {
                return ResourceManager.GetString("Erro_AssumirTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar a tarefa..
        /// </summary>
        public static string Erro_AtualizarTarefa {
            get {
                return ResourceManager.GetString("Erro_AtualizarTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo da tarefa nao encontrado..
        /// </summary>
        public static string Erro_CargoNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_CargoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo informado nao pertence ao departamento da tarefa..
        /// </summary>
        public static string Erro_CargoNaoPertenceDepartamento {
            get {
                return ResourceManager.GetString("Erro_CargoNaoPertenceDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O codigo de {0} informado e invalido. Quantidade de caracteres maior que 10 digitos, tente novamente..
        /// </summary>
        public static string Erro_CodigoTamanhoMaximo {
            get {
                return ResourceManager.GetString("Erro_CodigoTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O codigo de {0} informado e invalido. Quantidade de caracteres menor que 3 digitos, tente novamente..
        /// </summary>
        public static string Erro_CodigoTamanhoMinimo {
            get {
                return ResourceManager.GetString("Erro_CodigoTamanhoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O conteudo da tarefa informada e invalido. Quantidade de caracteres maior que 2500 digitos, tente novamente..
        /// </summary>
        public static string Erro_ConteudoTamanhoMaximo {
            get {
                return ResourceManager.GetString("Erro_ConteudoTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao foi possivel criar a solicitacao..
        /// </summary>
        public static string Erro_CriarSolicitacao {
            get {
                return ResourceManager.GetString("Erro_CriarSolicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao foi possivel decidir a solicitacao..
        /// </summary>
        public static string Erro_DecidirSolicitacao {
            get {
                return ResourceManager.GetString("Erro_DecidirSolicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento da tarefa nao encontrado..
        /// </summary>
        public static string Erro_DepartamentoNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_DepartamentoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado da tarefa nao encontrado..
        /// </summary>
        public static string Erro_EstadoNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_EstadoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao gravar a tarefa..
        /// </summary>
        public static string Erro_GravarTarefa {
            get {
                return ResourceManager.GetString("Erro_GravarTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador de usuário é inválido..
        /// </summary>
        public static string Erro_IdentificadorUsuarioInvalido {
            get {
                return ResourceManager.GetString("Erro_IdentificadorUsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial da tarefa e maior que a data final. Tente novamente..
        /// </summary>
        public static string Erro_PeriodoInvalido {
            get {
                return ResourceManager.GetString("Erro_PeriodoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível registrar a movimentação da tarefa..
        /// </summary>
        public static string Erro_RegistrarMovimentacao {
            get {
                return ResourceManager.GetString("Erro_RegistrarMovimentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao remover a tarefa..
        /// </summary>
        public static string Erro_RemoverTarefa {
            get {
                return ResourceManager.GetString("Erro_RemoverTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja existe solicitacao pendente para esta tarefa..
        /// </summary>
        public static string Erro_SolicitacaoPendenteExistente {
            get {
                return ResourceManager.GetString("Erro_SolicitacaoPendenteExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta tarefa exige solicitacao de obtencao..
        /// </summary>
        public static string Erro_TarefaExigeSolicitacaoObtencao {
            get {
                return ResourceManager.GetString("Erro_TarefaExigeSolicitacaoObtencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa finalizada nao pode ser assumida..
        /// </summary>
        public static string Erro_TarefaFinalizadaNaoPodeSerAssumida {
            get {
                return ResourceManager.GetString("Erro_TarefaFinalizadaNaoPodeSerAssumida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa finalizada nao pode ser solicitada..
        /// </summary>
        public static string Erro_TarefaFinalizadaNaoPodeSerSolicitada {
            get {
                return ResourceManager.GetString("Erro_TarefaFinalizadaNaoPodeSerSolicitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa ja possui usuario responsavel..
        /// </summary>
        public static string Erro_TarefaJaPossuiUsuarioResponsavel {
            get {
                return ResourceManager.GetString("Erro_TarefaJaPossuiUsuarioResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa não encontrada..
        /// </summary>
        public static string Erro_TarefaNaoEncontrada {
            get {
                return ResourceManager.GetString("Erro_TarefaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta tarefa nao exige aprovacao para obtencao..
        /// </summary>
        public static string Erro_TarefaNaoExigeAprovacao {
            get {
                return ResourceManager.GetString("Erro_TarefaNaoExigeAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tarefa não pode ser assumida..
        /// </summary>
        public static string Erro_TarefaNaoPodeSerAssumida {
            get {
                return ResourceManager.GetString("Erro_TarefaNaoPodeSerAssumida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O titulo da tarefa informada e invalido. Quantidade de caracteres maior que 50 digitos, tente novamente..
        /// </summary>
        public static string Erro_TituloTamanhoMaximo {
            get {
                return ResourceManager.GetString("Erro_TituloTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação aprovada; tarefa atribuída a {0}. Estado atual: {1}..
        /// </summary>
        public static string Historico_DetalheAprovacao {
            get {
                return ResourceManager.GetString("Historico_DetalheAprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exigência de aprovação para obtenção atualizada..
        /// </summary>
        public static string Historico_DetalheAprovacaoAtualizada {
            get {
                return ResourceManager.GetString("Historico_DetalheAprovacaoAtualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da tarefa atualizados..
        /// </summary>
        public static string Historico_DetalheAtualizacao {
            get {
                return ResourceManager.GetString("Historico_DetalheAtualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo atualizado..
        /// </summary>
        public static string Historico_DetalheConteudoAtualizado {
            get {
                return ResourceManager.GetString("Historico_DetalheConteudoAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa criada no estado {0}..
        /// </summary>
        public static string Historico_DetalheCriacao {
            get {
                return ResourceManager.GetString("Historico_DetalheCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino ou escopo da tarefa atualizado..
        /// </summary>
        public static string Historico_DetalheEscopoAtualizado {
            get {
                return ResourceManager.GetString("Historico_DetalheEscopoAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado alterado de {0} para {1}..
        /// </summary>
        public static string Historico_DetalheEstadoAlterado {
            get {
                return ResourceManager.GetString("Historico_DetalheEstadoAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa obtida diretamente por {0}..
        /// </summary>
        public static string Historico_DetalheObtencao {
            get {
                return ResourceManager.GetString("Historico_DetalheObtencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período alterado de {0:dd/MM/yyyy} a {1:dd/MM/yyyy} para {2:dd/MM/yyyy} a {3:dd/MM/yyyy}..
        /// </summary>
        public static string Historico_DetalhePeriodoAlterado {
            get {
                return ResourceManager.GetString("Historico_DetalhePeriodoAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de {0} recusada; a tarefa permanece disponível..
        /// </summary>
        public static string Historico_DetalheRecusa {
            get {
                return ResourceManager.GetString("Historico_DetalheRecusa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável alterado de {0} para {1}..
        /// </summary>
        public static string Historico_DetalheResponsavelAlterado {
            get {
                return ResourceManager.GetString("Historico_DetalheResponsavelAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de obtenção enviada para {0}..
        /// </summary>
        public static string Historico_DetalheSolicitacao {
            get {
                return ResourceManager.GetString("Historico_DetalheSolicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título atualizado..
        /// </summary>
        public static string Historico_DetalheTituloAtualizado {
            get {
                return ResourceManager.GetString("Historico_DetalheTituloAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não informado.
        /// </summary>
        public static string Historico_ValorNaoInformado {
            get {
                return ResourceManager.GetString("Historico_ValorNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracoes de tarefas atualizadas com sucesso..
        /// </summary>
        public static string Mensagem_ConfiguracoesAtualizadas {
            get {
                return ResourceManager.GetString("Mensagem_ConfiguracoesAtualizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua solicitacao para obter a tarefa {0} foi aprovada..
        /// </summary>
        public static string Mensagem_NotificacaoSolicitacaoAprovada {
            get {
                return ResourceManager.GetString("Mensagem_NotificacaoSolicitacaoAprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua solicitacao para obter a tarefa {0} foi recusada..
        /// </summary>
        public static string Mensagem_NotificacaoSolicitacaoRecusada {
            get {
                return ResourceManager.GetString("Mensagem_NotificacaoSolicitacaoRecusada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitacao aprovada com sucesso..
        /// </summary>
        public static string Mensagem_SolicitacaoAprovada {
            get {
                return ResourceManager.GetString("Mensagem_SolicitacaoAprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitacao enviada com sucesso..
        /// </summary>
        public static string Mensagem_SolicitacaoEnviada {
            get {
                return ResourceManager.GetString("Mensagem_SolicitacaoEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} solicitou obter a tarefa {1}..
        /// </summary>
        public static string Mensagem_SolicitacaoRecebida {
            get {
                return ResourceManager.GetString("Mensagem_SolicitacaoRecebida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitacao recusada com sucesso..
        /// </summary>
        public static string Mensagem_SolicitacaoRecusada {
            get {
                return ResourceManager.GetString("Mensagem_SolicitacaoRecusada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa assumida com sucesso..
        /// </summary>
        public static string Mensagem_TarefaAssumida {
            get {
                return ResourceManager.GetString("Mensagem_TarefaAssumida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tarefa {0} foi atribuída a você..
        /// </summary>
        public static string Mensagem_TarefaAtribuidaUsuario {
            get {
                return ResourceManager.GetString("Mensagem_TarefaAtribuidaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa atualizada com sucesso..
        /// </summary>
        public static string Mensagem_TarefaAtualizada {
            get {
                return ResourceManager.GetString("Mensagem_TarefaAtualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa gravada com sucesso..
        /// </summary>
        public static string Mensagem_TarefaCriada {
            get {
                return ResourceManager.GetString("Mensagem_TarefaCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tarefa {0} foi adicionada ao seu quadro..
        /// </summary>
        public static string Mensagem_TarefaObtida {
            get {
                return ResourceManager.GetString("Mensagem_TarefaObtida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa removida com sucesso..
        /// </summary>
        public static string Mensagem_TarefaRemovida {
            get {
                return ResourceManager.GetString("Mensagem_TarefaRemovida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova tarefa atribuída.
        /// </summary>
        public static string Titulo_EmailTarefaAtribuida {
            get {
                return ResourceManager.GetString("Titulo_EmailTarefaAtribuida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitacao de tarefa aprovada.
        /// </summary>
        public static string Titulo_SolicitacaoAprovada {
            get {
                return ResourceManager.GetString("Titulo_SolicitacaoAprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitacao de obtencao recebida.
        /// </summary>
        public static string Titulo_SolicitacaoRecebida {
            get {
                return ResourceManager.GetString("Titulo_SolicitacaoRecebida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitacao de tarefa recusada.
        /// </summary>
        public static string Titulo_SolicitacaoRecusada {
            get {
                return ResourceManager.GetString("Titulo_SolicitacaoRecusada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova tarefa atribuída.
        /// </summary>
        public static string Titulo_TarefaAtribuida {
            get {
                return ResourceManager.GetString("Titulo_TarefaAtribuida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa adicionada ao seu quadro.
        /// </summary>
        public static string Titulo_TarefaObtida {
            get {
                return ResourceManager.GetString("Titulo_TarefaObtida", resourceCulture);
            }
        }
    }
}
