//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkspaceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkspaceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.WorkspaceResource", typeof(WorkspaceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código da empresa é obrigatório para workspace empresarial..
        /// </summary>
        public static string Erro_EmpresaCodigoObrigatorio {
            get {
                return ResourceManager.GetString("Erro_EmpresaCodigoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa não encontrada..
        /// </summary>
        public static string Erro_EmpresaNaoEncontrada {
            get {
                return ResourceManager.GetString("Erro_EmpresaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de empresa não são permitidos para este tipo de workspace..
        /// </summary>
        public static string Erro_EmpresaNaoPermitida {
            get {
                return ResourceManager.GetString("Erro_EmpresaNaoPermitida", resourceCulture);
            }
        }

        public static string Erro_CadastroTipoNaoDisponivel {
            get {
                return ResourceManager.GetString("Erro_CadastroTipoNaoDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do workspace deve possuir no máximo 150 caracteres..
        /// </summary>
        public static string Erro_NomeLongo {
            get {
                return ResourceManager.GetString("Erro_NomeLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do workspace é obrigatório..
        /// </summary>
        public static string Erro_NomeObrigatorio {
            get {
                return ResourceManager.GetString("Erro_NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar o workspace inicial..
        /// </summary>
        public static string Erro_Persistencia {
            get {
                return ResourceManager.GetString("Erro_Persistencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados do workspace são obrigatórios..
        /// </summary>
        public static string Erro_RegistroNulo {
            get {
                return ResourceManager.GetString("Erro_RegistroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo do workspace é inválido..
        /// </summary>
        public static string Erro_TipoInvalido {
            get {
                return ResourceManager.GetString("Erro_TipoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código do usuário é obrigatório..
        /// </summary>
        public static string Erro_UsuarioCodigoObrigatorio {
            get {
                return ResourceManager.GetString("Erro_UsuarioCodigoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string Erro_UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_UsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A empresa já possui um workspace..
        /// </summary>
        public static string Erro_WorkspaceEmpresaExistente {
            get {
                return ResourceManager.GetString("Erro_WorkspaceEmpresaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário já possui um workspace inicial..
        /// </summary>
        public static string Erro_WorkspaceInicialUsuarioExistente {
            get {
                return ResourceManager.GetString("Erro_WorkspaceInicialUsuarioExistente", resourceCulture);
            }
        }

        public static string Erro_WorkspaceNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_WorkspaceNaoEncontrado", resourceCulture);
            }
        }

        public static string Erro_ConviteInvalido {
            get {
                return ResourceManager.GetString("Erro_ConviteInvalido", resourceCulture);
            }
        }

        public static string Erro_ConviteWorkspacePessoal {
            get {
                return ResourceManager.GetString("Erro_ConviteWorkspacePessoal", resourceCulture);
            }
        }

        public static string Erro_ConviteRemetenteNaoMembro {
            get {
                return ResourceManager.GetString("Erro_ConviteRemetenteNaoMembro", resourceCulture);
            }
        }

        public static string Erro_ConvitePersistencia {
            get {
                return ResourceManager.GetString("Erro_ConvitePersistencia", resourceCulture);
            }
        }

        public static string Erro_ConviteUsuarioJaMembro {
            get {
                return ResourceManager.GetString("Erro_ConviteUsuarioJaMembro", resourceCulture);
            }
        }

        public static string Erro_ConviteConsumo {
            get {
                return ResourceManager.GetString("Erro_ConviteConsumo", resourceCulture);
            }
        }

        public static string Erro_ConviteComWorkspace {
            get {
                return ResourceManager.GetString("Erro_ConviteComWorkspace", resourceCulture);
            }
        }

        public static string Mensagem_ConviteCriado {
            get {
                return ResourceManager.GetString("Mensagem_ConviteCriado", resourceCulture);
            }
        }

        public static string Mensagem_ConviteAceito {
            get {
                return ResourceManager.GetString("Mensagem_ConviteAceito", resourceCulture);
            }
        }
    }
}
