//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Application.Resources.AtronStock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoriaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoriaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Application.Resources.AtronStock.CategoriaResource", typeof(CategoriaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma categoria cadastrada com o código {0}..
        /// </summary>
        public static string ErroCategoriaJaExiste {
            get {
                return ResourceManager.GetString("ErroCategoriaJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não encontrada para o código {0}..
        /// </summary>
        public static string ErroCategoriaNaoEncontrada {
            get {
                return ResourceManager.GetString("ErroCategoriaNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código é obrigatório..
        /// </summary>
        public static string ErroCodigoObrigatorio {
            get {
                return ResourceManager.GetString("ErroCodigoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do código excede o limite de 25 caracteres..
        /// </summary>
        public static string ErroCodigoTamanho {
            get {
                return ResourceManager.GetString("ErroCodigoTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Descrição é obrigatória..
        /// </summary>
        public static string ErroDescricaoObrigatoria {
            get {
                return ResourceManager.GetString("ErroDescricaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Descrição excede o limite de 50 caracteres..
        /// </summary>
        public static string ErroDescricaoTamanho {
            get {
                return ResourceManager.GetString("ErroDescricaoTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado ao atualizar a categoria..
        /// </summary>
        public static string ErroInesperadoAtualizar {
            get {
                return ResourceManager.GetString("ErroInesperadoAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status da categoria deve ser informado..
        /// </summary>
        public static string ErroStatusObrigatorio {
            get {
                return ResourceManager.GetString("ErroStatusObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria {0} atualizada em {1}. Descrição: {2}, Status: {3}..
        /// </summary>
        public static string HistoricoAtualizacao {
            get {
                return ResourceManager.GetString("HistoricoAtualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria {0} criada em {1}..
        /// </summary>
        public static string HistoricoCriacao {
            get {
                return ResourceManager.GetString("HistoricoCriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da categoria {0} alterado para {1} em {2}..
        /// </summary>
        public static string HistoricoStatusAlterado {
            get {
                return ResourceManager.GetString("HistoricoStatusAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string SucessoCadastro {
            get {
                return ResourceManager.GetString("SucessoCadastro", resourceCulture);
            }
        }
    }
}
