//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Application.Resources.AtronStock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClienteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClienteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Application.Resources.AtronStock.ClienteResource", typeof(ClienteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente {0} atualizado na data {1}.
        /// </summary>
        public static string ClienteAtualizadoDescricao {
            get {
                return ResourceManager.GetString("ClienteAtualizadoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não existe..
        /// </summary>
        public static string ErroClienteNaoExiste {
            get {
                return ResourceManager.GetString("ErroClienteNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado ao remover o cliente..
        /// </summary>
        public static string ErroInesperadoAoRemover {
            get {
                return ResourceManager.GetString("ErroInesperadoAoRemover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado ao salvar o cliente..
        /// </summary>
        public static string ErroInesperadoCliente {
            get {
                return ResourceManager.GetString("ErroInesperadoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente {0} foi {1} na data {2}.
        /// </summary>
        public static string HistoricoClienteAtivado {
            get {
                return ResourceManager.GetString("HistoricoClienteAtivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente gravado com o código {0} e nome {1} na data {2}.
        /// </summary>
        public static string HistoricoClienteGravado {
            get {
                return ResourceManager.GetString("HistoricoClienteGravado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente {0} removido na data {1}.
        /// </summary>
        public static string HistoricoClienteRemovido {
            get {
                return ResourceManager.GetString("HistoricoClienteRemovido", resourceCulture);
            }
        }
    }
}
