//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Application.Resources.AtronStock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FornecedoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FornecedoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Application.Resources.AtronStock.FornecedoResource", typeof(FornecedoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um fornecedor cadastrado com o código informado..
        /// </summary>
        public static string ErroCodigoFornecedorExistente {
            get {
                return ResourceManager.GetString("ErroCodigoFornecedorExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código do fornecedor não pode exceder 20 caracteres..
        /// </summary>
        public static string ErroCodigoLimiteMaximoDeCaractere {
            get {
                return ResourceManager.GetString("ErroCodigoLimiteMaximoDeCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código do fornecedor deve ter no mínimo 3 caracteres..
        /// </summary>
        public static string ErroCodigoLimiteMinimoDeCaractere {
            get {
                return ResourceManager.GetString("ErroCodigoLimiteMinimoDeCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código do fornecedor é obrigatório..
        /// </summary>
        public static string ErroCodigoObrigatorio {
            get {
                return ResourceManager.GetString("ErroCodigoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do fornecedor tem um limite máximo de 100 caracteres..
        /// </summary>
        public static string ErroNomeLimiteMaximoDeCaractere {
            get {
                return ResourceManager.GetString("ErroNomeLimiteMaximoDeCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do fornecedor tem um limite mínimo de 5 caracteres.
        /// </summary>
        public static string ErroNomeLimiteMinimoDeCaractere {
            get {
                return ResourceManager.GetString("ErroNomeLimiteMinimoDeCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do fornecedor é obrigatório..
        /// </summary>
        public static string ErroNomeObrigatorio {
            get {
                return ResourceManager.GetString("ErroNomeObrigatorio", resourceCulture);
            }
        }
    }
}
