<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>Application</RootNamespace>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\AtronTracker.Domain.csproj" />
		<ProjectReference Include="..\..\..\..\Framework\Shared\Shared.csproj" />
		<ProjectReference Include="..\..\..\..\Framework\AtronNotificacoes\AtronNotificacoes.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\ModuloResource.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ModuloResource.resx</DependentUpon>
		</Compile>
		<Compile Update="Resources\PerfilDeAcessoResource.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>PerfilDeAcessoResource.resx</DependentUpon>
		</Compile>
		<Compile Update="Resources\PlanejamentoCustoResource.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>PlanejamentoCustoResource.resx</DependentUpon>
		</Compile>
		<Compile Update="Resources\TarefaResource.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>TarefaResource.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Email\Templates\pt-BR\confirmacao-cadastro.html">
			<LogicalName>Application.Email.Templates.pt-BR.confirmacao-cadastro.html</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Email\Templates\pt-BR\recuperacao-senha.html">
			<LogicalName>Application.Email.Templates.pt-BR.recuperacao-senha.html</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Email\Templates\pt-BR\confirmacao-concluida.html">
			<LogicalName>Application.Email.Templates.pt-BR.confirmacao-concluida.html</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Email\Templates\pt-BR\primeiro-acesso.html">
			<LogicalName>Application.Email.Templates.pt-BR.primeiro-acesso.html</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Email\Templates\pt-BR\alteracao-email.html">
			<LogicalName>Application.Email.Templates.pt-BR.alteracao-email.html</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Email\Templates\pt-BR\reativacao-conta.html">
			<LogicalName>Application.Email.Templates.pt-BR.reativacao-conta.html</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Email\Templates\pt-BR\tarefa-atribuida.html">
			<LogicalName>Application.Email.Templates.pt-BR.tarefa-atribuida.html</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\ModuloResource.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>ModuloResource.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\PerfilDeAcessoResource.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>PerfilDeAcessoResource.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\PlanejamentoCustoResource.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>PlanejamentoCustoResource.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\TarefaResource.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>TarefaResource.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="UseCases\DepartamentoCases\" />
	</ItemGroup>

</Project>
