// <auto-generated />
using AtronTracker.Infrastructure.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AtronTracker.Infrastructure.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(AtronDbContext))]
    [Migration("20260708120000_IncluindoPreferenciaNotificacaoInternaTarefa")]
    partial class IncluindoPreferenciaNotificacaoInternaTarefa
    {
    }
}
