//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DepartamentoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DepartamentoResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Application.Resources.DepartamentoResource", typeof(DepartamentoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código do departamento informado está cadastrado no sistema..
        /// </summary>
        public static string ErroCodigoDepartamentoExistente {
            get {
                return ResourceManager.GetString("ErroCodigoDepartamentoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código informado é muito longo. Tamanho máximo permitido de até 10 caracteres..
        /// </summary>
        public static string ErroCodigoLongo {
            get {
                return ResourceManager.GetString("ErroCodigoLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código do departamento não está preenchido..
        /// </summary>
        public static string ErroCodigoNulo {
            get {
                return ResourceManager.GetString("ErroCodigoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código informado é muito pequeno. Tamanho mínimo permitido de até 3 caracteres..
        /// </summary>
        public static string ErroCodigoPequeno {
            get {
                return ResourceManager.GetString("ErroCodigoPequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O departamento {0} contém relacionamentos pendentes que impedem a sua exclusão..
        /// </summary>
        public static string ErroDepartamentoContemRelacionamento {
            get {
                return ResourceManager.GetString("ErroDepartamentoContemRelacionamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição é muito longa. Tamanho máximo permitido de até 50 caracteres..
        /// </summary>
        public static string ErroDescricaoLonga {
            get {
                return ResourceManager.GetString("ErroDescricaoLonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição do departamento não está preenchida..
        /// </summary>
        public static string ErroDescricaoNula {
            get {
                return ResourceManager.GetString("ErroDescricaoNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição informada é muito pequena. Tamanho mínimo permitido de até 3 caracteres.
        /// </summary>
        public static string ErroDescricaoPequena {
            get {
                return ResourceManager.GetString("ErroDescricaoPequena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gestor do departamento nao encontrado..
        /// </summary>
        public static string ErroGestorNaoEncontrado {
            get {
                return ResourceManager.GetString("ErroGestorNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma falha ao gravar o departamento..
        /// </summary>
        public static string ErroGravacao {
            get {
                return ResourceManager.GetString("ErroGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro inesperado ao atualizar o departamento {0}..
        /// </summary>
        public static string ErroInesperadoAtualizacao {
            get {
                return ResourceManager.GetString("ErroInesperadoAtualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma falha na remoção do departamento {0}..
        /// </summary>
        public static string ErroRemocao {
            get {
                return ResourceManager.GetString("ErroRemocao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Departamento {0} atualizado com sucesso..
        /// </summary>
        public static string MensagemAtualizacao {
            get {
                return ResourceManager.GetString("MensagemAtualizacao", resourceCulture);
            }
        }
    }
}
