//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Application.Resources.EmailResource", typeof(EmailResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirme a alteração do seu e-mail - AtronTracker.
        /// </summary>
        public static string Assunto_AlteracaoEmail {
            get {
                return ResourceManager.GetString("Assunto_AlteracaoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirme seu cadastro - Atron Platform.
        /// </summary>
        public static string Assunto_ConfirmeCadastro {
            get {
                return ResourceManager.GetString("Assunto_ConfirmeCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail confirmado -  Atron Platform.
        /// </summary>
        public static string Assunto_EmailConfirmado {
            get {
                return ResourceManager.GetString("Assunto_EmailConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Defina sua senha de acesso - Sistema Atron.
        /// </summary>
        public static string Assunto_PrimeiroAcesso {
            get {
                return ResourceManager.GetString("Assunto_PrimeiroAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de reativação — Atron.
        /// </summary>
        public static string Assunto_ReativacaoConta {
            get {
                return ResourceManager.GetString("Assunto_ReativacaoConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recuperação de Senha - Atron Platform.
        /// </summary>
        public static string Assunto_RecuperacaoSenha {
            get {
                return ResourceManager.GetString("Assunto_RecuperacaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível gerar o código de confirmação..
        /// </summary>
        public static string Erro_CriarCodigoDeConfirmacao {
            get {
                return ResourceManager.GetString("Erro_CriarCodigoDeConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail desta conta já foi confirmado..
        /// </summary>
        public static string Erro_EmailConfirmado {
            get {
                return ResourceManager.GetString("Erro_EmailConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail ainda não confirmado. Enviamos um novo código de confirmacao para o e-mail cadastrado..
        /// </summary>
        public static string Erro_EmailNaoConfirmado {
            get {
                return ResourceManager.GetString("Erro_EmailNaoConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível reenviar o e-mail de confirmação:  {0}.
        /// </summary>
        public static string Erro_ExcesaoEnvioEmail {
            get {
                return ResourceManager.GetString("Erro_ExcesaoEnvioEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe o código ou e-mail do usuário..
        /// </summary>
        public static string Erro_InformeEmailCodigo {
            get {
                return ResourceManager.GetString("Erro_InformeEmailCodigo", resourceCulture);
            }
        }

        public static string Erro_TemplateAssuntoObrigatorio => ResourceManager.GetString("Erro_TemplateAssuntoObrigatorio", resourceCulture);

        public static string Erro_TemplateBaseCamposNaoRenderizados => ResourceManager.GetString("Erro_TemplateBaseCamposNaoRenderizados", resourceCulture);

        public static string Erro_TemplateCampoObrigatorio => ResourceManager.GetString("Erro_TemplateCampoObrigatorio", resourceCulture);

        public static string Erro_TemplateCamposNaoRenderizados => ResourceManager.GetString("Erro_TemplateCamposNaoRenderizados", resourceCulture);

        public static string Erro_TemplateDefinicaoObrigatoria => ResourceManager.GetString("Erro_TemplateDefinicaoObrigatoria", resourceCulture);

        public static string Erro_TemplateDestinatarioObrigatorio => ResourceManager.GetString("Erro_TemplateDestinatarioObrigatorio", resourceCulture);

        public static string Erro_TemplateModeloObrigatorio => ResourceManager.GetString("Erro_TemplateModeloObrigatorio", resourceCulture);

        public static string Erro_TemplateModeloSemCampo => ResourceManager.GetString("Erro_TemplateModeloSemCampo", resourceCulture);

        public static string Erro_TemplateNaoEncontrado => ResourceManager.GetString("Erro_TemplateNaoEncontrado", resourceCulture);

        public static string Erro_TemplateNomeInvalido => ResourceManager.GetString("Erro_TemplateNomeInvalido", resourceCulture);

        public static string Erro_TemplateRenderizacao => ResourceManager.GetString("Erro_TemplateRenderizacao", resourceCulture);

        public static string Erro_TemplateTituloObrigatorio => ResourceManager.GetString("Erro_TemplateTituloObrigatorio", resourceCulture);

        public static string Erro_TemplateUrlInvalida => ResourceManager.GetString("Erro_TemplateUrlInvalida", resourceCulture);
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações não encontradas para o provedor: {0}.
        /// </summary>
        public static string ErroConfiguracoesProvedor {
            get {
                return ResourceManager.GetString("ErroConfiguracoesProvedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail informado já está cadastrado no sistema..
        /// </summary>
        public static string ErroEmailUtilizado {
            get {
                return ResourceManager.GetString("ErroEmailUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Provedor de e-mail não suportado. Os provedores suportados são: Gmail, Outlook (Hotmail/Live/MSN) e Yahoo..
        /// </summary>
        public static string ErroProvedorDesconhecido {
            get {
                return ResourceManager.GetString("ErroProvedorDesconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enviamos um novo codigo de confirmacao para seu e-mail..
        /// </summary>
        public static string Mensagem_EnvioConfirmacaoEmail {
            get {
                return ResourceManager.GetString("Mensagem_EnvioConfirmacaoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alteração de E-mail.
        /// </summary>
        public static string Titulo_AlteracaoEmail {
            get {
                return ResourceManager.GetString("Titulo_AlteracaoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirme seu e-mail.
        /// </summary>
        public static string Titulo_ConfirmacaoCadastro {
            get {
                return ResourceManager.GetString("Titulo_ConfirmacaoCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail confirmado.
        /// </summary>
        public static string Titulo_EmailConfirmado {
            get {
                return ResourceManager.GetString("Titulo_EmailConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem-vindo ao Sistema Atron.
        /// </summary>
        public static string Titulo_PrimeiroAcesso {
            get {
                return ResourceManager.GetString("Titulo_PrimeiroAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reativação de Conta — Sistema Atron.
        /// </summary>
        public static string Titulo_ReativacaoConta {
            get {
                return ResourceManager.GetString("Titulo_ReativacaoConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recuperação de Senha.
        /// </summary>
        public static string Titulo_RecuperacaoSenha {
            get {
                return ResourceManager.GetString("Titulo_RecuperacaoSenha", resourceCulture);
            }
        }
    }
}
