//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailDiagnosticResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailDiagnosticResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Application.Resources.EmailDiagnosticResource", typeof(EmailDiagnosticResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [AUTO-DIAGNÓSTICO] Validação de configuração de e-mail.
        /// </summary>
        public static string Assunto_AutoDiagnostico {
            get {
                return ResourceManager.GetString("Assunto_AutoDiagnostico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [DIAGNÓSTICO] Verificação do serviço de e-mail - {0}.
        /// </summary>
        public static string Assunto_DiagnosticoPadrao {
            get {
                return ResourceManager.GetString("Assunto_DiagnosticoPadrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &apos;emailsDestino&apos; deve ser preenchido..
        /// </summary>
        public static string Detalhe_DestinoObrigatorio {
            get {
                return ResourceManager.GetString("Detalhe_DestinoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a API key da Brevo não configurada..
        /// </summary>
        public static string Erro_ApiKeyBrevoNaoConfigurada {
            get {
                return ResourceManager.GetString("Erro_ApiKeyBrevoNaoConfigurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail de destino é obrigatório..
        /// </summary>
        public static string Erro_DestinoObrigatorio {
            get {
                return ResourceManager.GetString("Erro_DestinoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao enviar e-mail de diagnóstico..
        /// </summary>
        public static string Erro_EnvioDiagnostico {
            get {
                return ResourceManager.GetString("Erro_EnvioDiagnostico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do remetente não configurado..
        /// </summary>
        public static string Erro_NomeRemetenteNaoConfigurado {
            get {
                return ResourceManager.GetString("Erro_NomeRemetenteNaoConfigurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Provedor de e-mail não suportado..
        /// </summary>
        public static string Erro_ProvedorNaoSuportado {
            get {
                return ResourceManager.GetString("Erro_ProvedorNaoSuportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail do remetente não configurado..
        /// </summary>
        public static string Erro_RemetenteNaoConfigurado {
            get {
                return ResourceManager.GetString("Erro_RemetenteNaoConfigurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha do remetente não configurada..
        /// </summary>
        public static string Erro_SenhaRemetenteNaoConfigurada {
            get {
                return ResourceManager.GetString("Erro_SenhaRemetenteNaoConfigurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este e-mail foi enviado automaticamente para validar que as configurações estão funcionando corretamente..
        /// </summary>
        public static string Mensagem_AutoDiagnostico {
            get {
                return ResourceManager.GetString("Mensagem_AutoDiagnostico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este é um e-mail de diagnóstico para validar a configuração de envio do Sistema Atron..
        /// </summary>
        public static string Mensagem_CorpoPadrao {
            get {
                return ResourceManager.GetString("Mensagem_CorpoPadrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Serviço de e-mail não está configurado corretamente..
        /// </summary>
        public static string Mensagem_ServicoNaoConfigurado {
            get {
                return ResourceManager.GetString("Mensagem_ServicoNaoConfigurado", resourceCulture);
            }
        }
    }
}
