//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificacoesPadronizadas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificacoesPadronizadas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Application.Resources.NotificacoesPadronizadas", typeof(NotificacoesPadronizadas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro {0} já existe..
        /// </summary>
        public static string Erro_RegistroComDescricaoExistente {
            get {
                return ResourceManager.GetString("Erro_RegistroComDescricaoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro {0} inválido.
        /// </summary>
        public static string Erro_RegistroComDescricaoInvalido {
            get {
                return ResourceManager.GetString("Erro_RegistroComDescricaoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro {0} não encontrado..
        /// </summary>
        public static string Erro_RegistroComDescricaoNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_RegistroComDescricaoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo está inválido ou não preenchido..
        /// </summary>
        public static string ErroCampoInvalido {
            get {
                return ResourceManager.GetString("ErroCampoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string ErroCampoObrigatorio {
            get {
                return ResourceManager.GetString("ErroCampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código na URL não corresponde ao código no corpo da requisição..
        /// </summary>
        public static string ErroCodigoRotaDivergente {
            get {
                return ResourceManager.GetString("ErroCodigoRotaDivergente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado..
        /// </summary>
        public static string ErroRegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("ErroRegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro inválido ou não preenchido..
        /// </summary>
        public static string ErroRegistroNulo {
            get {
                return ResourceManager.GetString("ErroRegistroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo de tamanho inválido para o campo {0}..
        /// </summary>
        public static string IntervaloDeTamanhoInvalido {
            get {
                return ResourceManager.GetString("IntervaloDeTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} salvo com sucesso..
        /// </summary>
        public static string Mensagem_EntidadeSalva {
            get {
                return ResourceManager.GetString("Mensagem_EntidadeSalva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro {0} atualizado com sucesso..
        /// </summary>
        public static string Mensagem_RegistroAtualizado {
            get {
                return ResourceManager.GetString("Mensagem_RegistroAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro {0} removido com sucesso.
        /// </summary>
        public static string Mensagem_RegistroRemovido {
            get {
                return ResourceManager.GetString("Mensagem_RegistroRemovido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro {0} salvo com sucesso..
        /// </summary>
        public static string Mensagem_RegistroSalvo {
            get {
                return ResourceManager.GetString("Mensagem_RegistroSalvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removido com sucesso.
        /// </summary>
        public static string Mensagem_RemocaoSucessoSemRegistro {
            get {
                return ResourceManager.GetString("Mensagem_RemocaoSucessoSemRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro removido com sucesso..
        /// </summary>
        public static string MensagemRemocaoSucesso {
            get {
                return ResourceManager.GetString("MensagemRemocaoSucesso", resourceCulture);
            }
        }
    }
}
