//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsuarioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsuarioResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Application.Resources.UsuarioResource", typeof(UsuarioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inativo..
        /// </summary>
        public static string Erro_UsuarioInativo {
            get {
                return ResourceManager.GetString("Erro_UsuarioInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string Erro_UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_UsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código informado é muito longo. Tamanho máximo permitido de até 10 caracteres..
        /// </summary>
        public static string ErroCodigoLongo {
            get {
                return ResourceManager.GetString("ErroCodigoLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo código não está preenchido..
        /// </summary>
        public static string ErroCodigoNulo {
            get {
                return ResourceManager.GetString("ErroCodigoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código informado é muito pequeno. Tamanho mínimo permitido de até 3 caracteres..
        /// </summary>
        public static string ErroCodigoPequeno {
            get {
                return ResourceManager.GetString("ErroCodigoPequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de reativação inválido..
        /// </summary>
        public static string ErroCodigoReativacaoInvalido {
            get {
                return ResourceManager.GetString("ErroCodigoReativacaoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao confirmar alteração. Token inválido ou expirado..
        /// </summary>
        public static string ErroConfirmacaoAlteracaoEmail {
            get {
                return ResourceManager.GetString("ErroConfirmacaoAlteracaoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados inválidos para confirmação..
        /// </summary>
        public static string ErroDadosConfirmacaoAlteracaoEmail {
            get {
                return ResourceManager.GetString("ErroDadosConfirmacaoAlteracaoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento inválida..
        /// </summary>
        public static string ErroDataDeNascimento {
            get {
                return ResourceManager.GetString("ErroDataDeNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este e-mail já está em uso por outro usuário..
        /// </summary>
        public static string ErroEmailEmUso {
            get {
                return ResourceManager.GetString("ErroEmailEmUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail é obrigatório..
        /// </summary>
        public static string ErroEmailNulo {
            get {
                return ResourceManager.GetString("ErroEmailNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestor imediato nao encontrado..
        /// </summary>
        public static string ErroGestorNaoEncontrado {
            get {
                return ResourceManager.GetString("ErroGestorNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuario nao pode ser gestor imediato dele mesmo..
        /// </summary>
        public static string ErroGestorProprio {
            get {
                return ResourceManager.GetString("ErroGestorProprio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado ao atualizar usuário..
        /// </summary>
        public static string ErroInesperadoAtualizacao {
            get {
                return ResourceManager.GetString("ErroInesperadoAtualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado ao criar usuário..
        /// </summary>
        public static string ErroInesperadoGravacao {
            get {
                return ResourceManager.GetString("ErroInesperadoGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é muito longo. Tamanho máximo permitido de até 25 caracteres..
        /// </summary>
        public static string ErroNomeLongo {
            get {
                return ResourceManager.GetString("ErroNomeLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é muito pequeno. Tamanho mínimo permitido de até 3 caracteres..
        /// </summary>
        public static string ErroNomePequeno {
            get {
                return ResourceManager.GetString("ErroNomePequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário é obrigatório..
        /// </summary>
        public static string ErroNomeUsuarioNulo {
            get {
                return ResourceManager.GetString("ErroNomeUsuarioNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O novo e-mail não pode ser vazio..
        /// </summary>
        public static string ErroNovoEmailVazio {
            get {
                return ResourceManager.GetString("ErroNovoEmailVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro nulo.
        /// </summary>
        public static string ErroRegistroNulo {
            get {
                return ResourceManager.GetString("ErroRegistroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível remover o usuário..
        /// </summary>
        public static string ErroRemoverUsuario {
            get {
                return ResourceManager.GetString("ErroRemoverUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível repassar as tarefas para o quadro do departamento do usuário..
        /// </summary>
        public static string ErroRepassarTarefasUsuario {
            get {
                return ResourceManager.GetString("ErroRepassarTarefasUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos um caractere especial..
        /// </summary>
        public static string ErroSenhaCaractereEspecial {
            get {
                return ResourceManager.GetString("ErroSenhaCaractereEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter letras maiúsculas, minúsculas e pelo menos um número..
        /// </summary>
        public static string ErroSenhaComposicao {
            get {
                return ResourceManager.GetString("ErroSenhaComposicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha vazia ou não informada..
        /// </summary>
        public static string ErroSenhaNula {
            get {
                return ResourceManager.GetString("ErroSenhaNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas não são iguais.
        /// </summary>
        public static string ErroSenhasDiferentes {
            get {
                return ResourceManager.GetString("ErroSenhasDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter mais de 8 caracteres.
        /// </summary>
        public static string ErroSenhaTamanhoMinimo {
            get {
                return ResourceManager.GetString("ErroSenhaTamanhoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome é muito longo. Tamanho máximo permitido de até 50 caracteres..
        /// </summary>
        public static string ErroSobrenomeLongo {
            get {
                return ResourceManager.GetString("ErroSobrenomeLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome de usuário é obrigatório..
        /// </summary>
        public static string ErroSobrenomeObrigatorio {
            get {
                return ResourceManager.GetString("ErroSobrenomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome é muito pequeno.Tamanho mínimo permitido de até 3 caracteres..
        /// </summary>
        public static string ErroSobrenomePequeno {
            get {
                return ResourceManager.GetString("ErroSobrenomePequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de usuário informado já existe. Tente outro novamente..
        /// </summary>
        public static string ErroUsuarioExistente {
            get {
                return ResourceManager.GetString("ErroUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já está inativo.
        /// </summary>
        public static string ErroUsuarioJaInativo {
            get {
                return ResourceManager.GetString("ErroUsuarioJaInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro inválido ou não preenchido..
        /// </summary>
        public static string ErroUsuarioNulo {
            get {
                return ResourceManager.GetString("ErroUsuarioNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário cadastrado com sucesso..
        /// </summary>
        public static string Mensagem_UsuarioSalvo {
            get {
                return ResourceManager.GetString("Mensagem_UsuarioSalvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de reativação enviado para o e-mail cadastrado..
        /// </summary>
        public static string MensagemCodigoReativacaoEnviado {
            get {
                return ResourceManager.GetString("MensagemCodigoReativacaoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta reativada com sucesso..
        /// </summary>
        public static string MensagemContaReativada {
            get {
                return ResourceManager.GetString("MensagemContaReativada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail alterado com sucesso..
        /// </summary>
        public static string MensagemEmailAlterado {
            get {
                return ResourceManager.GetString("MensagemEmailAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de alteração enviada. Verifique o novo e-mail para confirmar..
        /// </summary>
        public static string MensagemSolicitacaoAlteracaoEmail {
            get {
                return ResourceManager.GetString("MensagemSolicitacaoAlteracaoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário atualizado com sucesso..
        /// </summary>
        public static string MensagemUsuarioAtualizado {
            get {
                return ResourceManager.GetString("MensagemUsuarioAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario {0} {1} salvo com sucesso. O link de primeiro acesso foi enviado por e-mail..
        /// </summary>
        public static string MensagemUsuarioCriadoPrimeiroAcesso {
            get {
                return ResourceManager.GetString("MensagemUsuarioCriadoPrimeiroAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário desativado com sucesso..
        /// </summary>
        public static string MensagemUsuarioDesativado {
            get {
                return ResourceManager.GetString("MensagemUsuarioDesativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário removido com sucesso..
        /// </summary>
        public static string MensagemUsuarioRemovido {
            get {
                return ResourceManager.GetString("MensagemUsuarioRemovido", resourceCulture);
            }
        }
    }
}
