//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsuarioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsuarioResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Application.Resources.UsuarioResource", typeof(UsuarioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário inativo..
        /// </summary>
        public static string Erro_UsuarioInativo {
            get {
                return ResourceManager.GetString("Erro_UsuarioInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado..
        /// </summary>
        public static string Erro_UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_UsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código informado é muito longo. Tamanho máximo permitido de até 10 caracteres..
        /// </summary>
        public static string ErroCodigoLongo {
            get {
                return ResourceManager.GetString("ErroCodigoLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo código não está preenchido..
        /// </summary>
        public static string ErroCodigoNulo {
            get {
                return ResourceManager.GetString("ErroCodigoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código informado é muito pequeno. Tamanho mínimo permitido de até 3 caracteres..
        /// </summary>
        public static string ErroCodigoPequeno {
            get {
                return ResourceManager.GetString("ErroCodigoPequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de reativação inválido..
        /// </summary>
        public static string ErroCodigoReativacaoInvalido {
            get {
                return ResourceManager.GetString("ErroCodigoReativacaoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao confirmar alteração. Token inválido ou expirado..
        /// </summary>
        public static string ErroConfirmacaoAlteracaoEmail {
            get {
                return ResourceManager.GetString("ErroConfirmacaoAlteracaoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados inválidos para confirmação..
        /// </summary>
        public static string ErroDadosConfirmacaoAlteracaoEmail {
            get {
                return ResourceManager.GetString("ErroDadosConfirmacaoAlteracaoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de nascimento inválida..
        /// </summary>
        public static string ErroDataDeNascimento {
            get {
                return ResourceManager.GetString("ErroDataDeNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este e-mail já está em uso por outro usuário..
        /// </summary>
        public static string ErroEmailEmUso {
            get {
                return ResourceManager.GetString("ErroEmailEmUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail é obrigatório..
        /// </summary>
        public static string ErroEmailNulo {
            get {
                return ResourceManager.GetString("ErroEmailNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gestor imediato nao encontrado..
        /// </summary>
        public static string ErroGestorNaoEncontrado {
            get {
                return ResourceManager.GetString("ErroGestorNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario nao pode ser gestor imediato dele mesmo..
        /// </summary>
        public static string ErroGestorProprio {
            get {
                return ResourceManager.GetString("ErroGestorProprio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro inesperado ao atualizar usuário..
        /// </summary>
        public static string ErroInesperadoAtualizacao {
            get {
                return ResourceManager.GetString("ErroInesperadoAtualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro inesperado ao criar usuário..
        /// </summary>
        public static string ErroInesperadoGravacao {
            get {
                return ResourceManager.GetString("ErroInesperadoGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome é muito longo. Tamanho máximo permitido de até 25 caracteres..
        /// </summary>
        public static string ErroNomeLongo {
            get {
                return ResourceManager.GetString("ErroNomeLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome é muito pequeno. Tamanho mínimo permitido de até 3 caracteres..
        /// </summary>
        public static string ErroNomePequeno {
            get {
                return ResourceManager.GetString("ErroNomePequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de usuário é obrigatório..
        /// </summary>
        public static string ErroNomeUsuarioNulo {
            get {
                return ResourceManager.GetString("ErroNomeUsuarioNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O novo e-mail não pode ser vazio..
        /// </summary>
        public static string ErroNovoEmailVazio {
            get {
                return ResourceManager.GetString("ErroNovoEmailVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro nulo.
        /// </summary>
        public static string ErroRegistroNulo {
            get {
                return ResourceManager.GetString("ErroRegistroNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos um caractere especial..
        /// </summary>
        public static string ErroSenhaCaractereEspecial {
            get {
                return ResourceManager.GetString("ErroSenhaCaractereEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter letras maiúsculas, minúsculas e pelo menos um número..
        /// </summary>
        public static string ErroSenhaComposicao {
            get {
                return ResourceManager.GetString("ErroSenhaComposicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha vazia ou não informada..
        /// </summary>
        public static string ErroSenhaNula {
            get {
                return ResourceManager.GetString("ErroSenhaNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As senhas não são iguais.
        /// </summary>
        public static string ErroSenhasDiferentes {
            get {
                return ResourceManager.GetString("ErroSenhasDiferentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter mais de 8 caracteres.
        /// </summary>
        public static string ErroSenhaTamanhoMinimo {
            get {
                return ResourceManager.GetString("ErroSenhaTamanhoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O sobrenome é muito longo. Tamanho máximo permitido de até 50 caracteres..
        /// </summary>
        public static string ErroSobrenomeLongo {
            get {
                return ResourceManager.GetString("ErroSobrenomeLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobrenome de usuário é obrigatório..
        /// </summary>
        public static string ErroSobrenomeObrigatorio {
            get {
                return ResourceManager.GetString("ErroSobrenomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O sobrenome é muito pequeno.Tamanho mínimo permitido de até 3 caracteres..
        /// </summary>
        public static string ErroSobrenomePequeno {
            get {
                return ResourceManager.GetString("ErroSobrenomePequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de usuário informado já existe. Tente outro novamente..
        /// </summary>
        public static string ErroUsuarioExistente {
            get {
                return ResourceManager.GetString("ErroUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário já está inativo.
        /// </summary>
        public static string ErroUsuarioJaInativo {
            get {
                return ResourceManager.GetString("ErroUsuarioJaInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro inválido ou não preenchido..
        /// </summary>
        public static string ErroUsuarioNulo {
            get {
                return ResourceManager.GetString("ErroUsuarioNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de reativação enviado para o e-mail cadastrado..
        /// </summary>
        public static string MensagemCodigoReativacaoEnviado {
            get {
                return ResourceManager.GetString("MensagemCodigoReativacaoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta reativada com sucesso..
        /// </summary>
        public static string MensagemContaReativada {
            get {
                return ResourceManager.GetString("MensagemContaReativada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail alterado com sucesso..
        /// </summary>
        public static string MensagemEmailAlterado {
            get {
                return ResourceManager.GetString("MensagemEmailAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solicitação de alteração enviada. Verifique o novo e-mail para confirmar..
        /// </summary>
        public static string MensagemSolicitacaoAlteracaoEmail {
            get {
                return ResourceManager.GetString("MensagemSolicitacaoAlteracaoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário atualizado com sucesso..
        /// </summary>
        public static string MensagemUsuarioAtualizado {
            get {
                return ResourceManager.GetString("MensagemUsuarioAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario {0} {1} salvo com sucesso. O link de primeiro acesso foi enviado por e-mail..
        /// </summary>
        public static string MensagemUsuarioCriadoPrimeiroAcesso {
            get {
                return ResourceManager.GetString("MensagemUsuarioCriadoPrimeiroAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário desativado com sucesso..
        /// </summary>
        public static string MensagemUsuarioDesativado {
            get {
                return ResourceManager.GetString("MensagemUsuarioDesativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário removido com sucesso..
        /// </summary>
        public static string MensagemUsuarioRemovido {
            get {
                return ResourceManager.GetString("MensagemUsuarioRemovido", resourceCulture);
            }
        }
    }
}
