//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsuarioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsuarioResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Application.Resources.UsuarioResource", typeof(UsuarioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código informado é muito longo. Tamanho máximo permitido de até 10 caracteres..
        /// </summary>
        public static string ErroCodigoLongo {
            get {
                return ResourceManager.GetString("ErroCodigoLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo código não está preenchido..
        /// </summary>
        public static string ErroCodigoNulo {
            get {
                return ResourceManager.GetString("ErroCodigoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código informado é muito pequeno. Tamanho mínimo permitido de até 3 caracteres..
        /// </summary>
        public static string ErroCodigoPequeno {
            get {
                return ResourceManager.GetString("ErroCodigoPequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento inválida..
        /// </summary>
        public static string ErroDataDeNascimento {
            get {
                return ResourceManager.GetString("ErroDataDeNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail é obrigatório..
        /// </summary>
        public static string ErroEmailNulo {
            get {
                return ResourceManager.GetString("ErroEmailNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado ao atualizar usuário..
        /// </summary>
        public static string ErroInesperadoAtualizacao {
            get {
                return ResourceManager.GetString("ErroInesperadoAtualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado ao criar usuário..
        /// </summary>
        public static string ErroInesperadoGravacao {
            get {
                return ResourceManager.GetString("ErroInesperadoGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é muito longo. Tamanho máximo permitido de até 25 caracteres..
        /// </summary>
        public static string ErroNomeLongo {
            get {
                return ResourceManager.GetString("ErroNomeLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é muito pequeno. Tamanho mínimo permitido de até 3 caracteres..
        /// </summary>
        public static string ErroNomePequeno {
            get {
                return ResourceManager.GetString("ErroNomePequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário é obrigatório..
        /// </summary>
        public static string ErroNomeUsuarioNulo {
            get {
                return ResourceManager.GetString("ErroNomeUsuarioNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome é muito longo. Tamanho máximo permitido de até 50 caracteres..
        /// </summary>
        public static string ErroSobrenomeLongo {
            get {
                return ResourceManager.GetString("ErroSobrenomeLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome de usuário é obrigatório..
        /// </summary>
        public static string ErroSobrenomeObrigatorio {
            get {
                return ResourceManager.GetString("ErroSobrenomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome é muito pequeno.Tamanho mínimo permitido de até 3 caracteres..
        /// </summary>
        public static string ErroSobrenomePequeno {
            get {
                return ResourceManager.GetString("ErroSobrenomePequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de usuário informado já existe. Tente outro novamente..
        /// </summary>
        public static string ErroUsuarioExistente {
            get {
                return ResourceManager.GetString("ErroUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro inválido ou não preenchido..
        /// </summary>
        public static string ErroUsuarioNulo {
            get {
                return ResourceManager.GetString("ErroUsuarioNulo", resourceCulture);
            }
        }
    }
}
