CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE SEQUENCE "HistoricoSeq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE TABLE "Auditorias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DataCriacao" timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    "DataAlteracao" timestamp without time zone NULL,
    "CriadoPor" character varying(25) NOT NULL,
    "AlteradoPor" character varying(25) NULL,
    "CodigoRegistro" character varying(50) NOT NULL,
    "Contexto" character varying(50) NOT NULL,
    "RemovidoEm" timestamp without time zone NULL,
    CONSTRAINT "PK_Auditorias" PRIMARY KEY ("Id")
);

CREATE TABLE "Historicos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodigoHistorico" bigint NOT NULL DEFAULT (nextval('"HistoricoSeq"')),
    "Contexto" character varying(50) NOT NULL,
    "CodigoRegistro" character varying(50) NOT NULL,
    "DataCriacao" timestamp without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    "Descricao" character varying(1500) NOT NULL,
    CONSTRAINT "PK_Historicos" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Auditorias_Contexto_CodigoRegistro" ON "Auditorias" ("Contexto", "CodigoRegistro");

CREATE INDEX "IX_Historicos_Contexto_CodigoRegistro" ON "Historicos" ("Contexto", "CodigoRegistro");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260623030029_InitialSharedPostgreSql', '6.0.32');

COMMIT;

