// <auto-generated />
using System;
using AtronNotificacoes.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtronNotificacoes.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(NotificacoesDbContext))]
    partial class NotificacoesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("notificacoes_ids")
                .StartsAt(1000001L);

            modelBuilder.Entity("AtronNotificacoes.Domain.NotificacaoInterna", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('notificacoes_ids')");

                    b.Property<string>("ChaveIdempotencia")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("CorrelacaoId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataExclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataLeitura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinatarioCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ModuloOrigem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("UrlDestino")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloOrigem", "ChaveIdempotencia")
                        .IsUnique()
                        .HasFilter("\"ChaveIdempotencia\" IS NOT NULL");

                    b.HasIndex("DestinatarioCodigo", "DataExclusao", "Lida", "DataCriacao");

                    b.ToTable("Notificacoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
