CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AppRole" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NULL,
    "NormalizedName" character varying(50) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AppRole" PRIMARY KEY ("Id")
);

CREATE TABLE "AppUser" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RefreshToken" character varying(1000) NULL,
    "RefreshTokenExpireTime" timestamp without time zone NULL,
    "UserName" character varying(50) NOT NULL,
    "NormalizedUserName" character varying(50) NULL,
    "Email" character varying(60) NOT NULL,
    "NormalizedEmail" character varying(60) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" character varying(450) NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" character varying(25) NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AppUser" PRIMARY KEY ("Id")
);

CREATE TABLE "Departamentos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Descricao" character varying(50) NOT NULL,
    CONSTRAINT "PK_Departamentos" PRIMARY KEY ("Id", "Codigo")
);

CREATE TABLE "Modulos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Descricao" character varying(100) NOT NULL,
    CONSTRAINT "PK_Modulos" PRIMARY KEY ("Id", "Codigo")
);

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Nome" character varying(25) NOT NULL,
    "Sobrenome" character varying(50) NOT NULL,
    "Email" character varying(50) NOT NULL,
    "DataNascimento" timestamp without time zone NULL,
    "SalarioAtual" integer NULL,
    "Inativo" boolean NOT NULL DEFAULT FALSE,
    "CodigoReativacao" character varying(6) NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id", "Codigo")
);

CREATE TABLE "AppRoleClaim" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" character varying(128) NULL,
    "ClaimValue" character varying(128) NULL,
    CONSTRAINT "PK_AppRoleClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AppRoleClaim_AppRole_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AppRole" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AppUserClaim" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" character varying(50) NULL,
    "ClaimValue" character varying(50) NULL,
    CONSTRAINT "PK_AppUserClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AppUserClaim_AppUser_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AppUserLogin" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AppUserLogin" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AppUserLogin_AppUser_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AppUserRole" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AppUserRole" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AppUserRole_AppRole_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AppRole" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AppUserRole_AppUser_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AppUserToken" (
    "UserId" integer NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Value" character varying(450) NULL,
    CONSTRAINT "PK_AppUserToken" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AppUserToken_AppUser_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Cargos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Descricao" character varying(50) NOT NULL,
    "DepartamentoId" integer NOT NULL,
    "DepartamentoCodigo" character varying(10) NULL,
    CONSTRAINT "PK_Cargos" PRIMARY KEY ("Id", "Codigo"),
    CONSTRAINT "FK_Cargos_Departamentos_DepartamentoId_DepartamentoCodigo" FOREIGN KEY ("DepartamentoId", "DepartamentoCodigo") REFERENCES "Departamentos" ("Id", "Codigo")
);

CREATE TABLE "PerfisDeAcesso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Descricao" character varying(50) NOT NULL,
    "UsuarioId" integer NULL,
    "UsuarioCodigo" character varying(10) NULL,
    CONSTRAINT "PK_PerfisDeAcesso" PRIMARY KEY ("Id", "Codigo"),
    CONSTRAINT "FK_PerfisDeAcesso_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo")
);

CREATE TABLE "Salarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "UsuarioCodigo" character varying(10) NOT NULL,
    "SalarioMensal" integer NOT NULL,
    "Ano" character varying(4) NOT NULL,
    "MesId" integer NOT NULL,
    CONSTRAINT "PK_Salarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Salarios_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE CASCADE
);

CREATE TABLE "Tarefas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "UsuarioCodigo" character varying(10) NULL,
    "Titulo" character varying(50) NOT NULL,
    "Conteudo" character varying(2500) NULL,
    "DataInicial" timestamp without time zone NOT NULL,
    "DataFinal" timestamp without time zone NOT NULL,
    "TarefaEstadoId" integer NOT NULL,
    CONSTRAINT "PK_Tarefas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tarefas_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo")
);

CREATE TABLE "UsuarioCargoDepartamento" (
    "UsuarioId" integer NOT NULL,
    "UsuarioCodigo" character varying(10) NOT NULL,
    "CargoId" integer NOT NULL,
    "CargoCodigo" character varying(10) NOT NULL,
    "DepartamentoId" integer NOT NULL,
    "DepartamentoCodigo" character varying(10) NOT NULL,
    CONSTRAINT "PK_UsuarioCargoDepartamento" PRIMARY KEY ("UsuarioId", "UsuarioCodigo", "CargoId", "CargoCodigo", "DepartamentoId", "DepartamentoCodigo"),
    CONSTRAINT "FK_UsuarioCargoDepartamento_Cargos_CargoId_CargoCodigo" FOREIGN KEY ("CargoId", "CargoCodigo") REFERENCES "Cargos" ("Id", "Codigo") ON DELETE CASCADE,
    CONSTRAINT "FK_UsuarioCargoDepartamento_Departamentos_DepartamentoId_Depar~" FOREIGN KEY ("DepartamentoId", "DepartamentoCodigo") REFERENCES "Departamentos" ("Id", "Codigo") ON DELETE CASCADE,
    CONSTRAINT "FK_UsuarioCargoDepartamento_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE CASCADE
);

CREATE TABLE "PerfilDeAcessoModulos" (
    "PerfilDeAcessoId" integer NOT NULL,
    "PerfilDeAcessoCodigo" character varying(10) NOT NULL,
    "ModuloId" integer NOT NULL,
    "ModuloCodigo" character varying(10) NOT NULL,
    CONSTRAINT "PK_PerfilDeAcessoModulos" PRIMARY KEY ("PerfilDeAcessoId", "PerfilDeAcessoCodigo", "ModuloId", "ModuloCodigo"),
    CONSTRAINT "FK_PerfilDeAcessoModulos_Modulos_ModuloId_ModuloCodigo" FOREIGN KEY ("ModuloId", "ModuloCodigo") REFERENCES "Modulos" ("Id", "Codigo") ON DELETE CASCADE,
    CONSTRAINT "FK_PerfilDeAcessoModulos_PerfisDeAcesso_PerfilDeAcessoId_Perfi~" FOREIGN KEY ("PerfilDeAcessoId", "PerfilDeAcessoCodigo") REFERENCES "PerfisDeAcesso" ("Id", "Codigo") ON DELETE CASCADE
);

CREATE TABLE "PerfilDeAcessoUsuarios" (
    "PerfilDeAcessoId" integer NOT NULL,
    "PerfilDeAcessoCodigo" character varying(10) NOT NULL,
    "UsuarioId" integer NOT NULL,
    "UsuarioCodigo" character varying(10) NOT NULL,
    CONSTRAINT "PK_PerfilDeAcessoUsuarios" PRIMARY KEY ("PerfilDeAcessoId", "PerfilDeAcessoCodigo", "UsuarioId", "UsuarioCodigo"),
    CONSTRAINT "FK_PerfilDeAcessoUsuarios_PerfisDeAcesso_PerfilDeAcessoId_Perf~" FOREIGN KEY ("PerfilDeAcessoId", "PerfilDeAcessoCodigo") REFERENCES "PerfisDeAcesso" ("Id", "Codigo") ON DELETE CASCADE,
    CONSTRAINT "FK_PerfilDeAcessoUsuarios_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE CASCADE
);

INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('DPT', 1, 'Departamentos');
INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('CRG', 2, 'Cargos');
INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('USR', 3, 'Usuários');
INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('TAR', 4, 'Tarefas');
INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('SAL', 5, 'Salários');
INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('PAC', 6, 'Políticas e Acessos');

CREATE UNIQUE INDEX "RoleNameIndex" ON "AppRole" ("NormalizedName");

CREATE INDEX "IX_AppRoleClaim_RoleId" ON "AppRoleClaim" ("RoleId");

CREATE INDEX "EmailIndex" ON "AppUser" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AppUser" ("NormalizedUserName");

CREATE INDEX "IX_AppUserClaim_UserId" ON "AppUserClaim" ("UserId");

CREATE INDEX "IX_AppUserLogin_UserId" ON "AppUserLogin" ("UserId");

CREATE INDEX "IX_AppUserRole_RoleId" ON "AppUserRole" ("RoleId");

CREATE INDEX "IX_Cargos_DepartamentoId_DepartamentoCodigo" ON "Cargos" ("DepartamentoId", "DepartamentoCodigo");

CREATE INDEX "IX_PerfilDeAcessoModulos_ModuloId_ModuloCodigo" ON "PerfilDeAcessoModulos" ("ModuloId", "ModuloCodigo");

CREATE INDEX "IX_PerfilDeAcessoUsuarios_UsuarioId_UsuarioCodigo" ON "PerfilDeAcessoUsuarios" ("UsuarioId", "UsuarioCodigo");

CREATE INDEX "IX_PerfisDeAcesso_UsuarioId_UsuarioCodigo" ON "PerfisDeAcesso" ("UsuarioId", "UsuarioCodigo");

CREATE UNIQUE INDEX "IX_Salarios_UsuarioId_UsuarioCodigo" ON "Salarios" ("UsuarioId", "UsuarioCodigo");

CREATE INDEX "IX_Tarefas_UsuarioId_UsuarioCodigo" ON "Tarefas" ("UsuarioId", "UsuarioCodigo");

CREATE INDEX "IX_UsuarioCargoDepartamento_CargoId_CargoCodigo" ON "UsuarioCargoDepartamento" ("CargoId", "CargoCodigo");

CREATE INDEX "IX_UsuarioCargoDepartamento_DepartamentoId_DepartamentoCodigo" ON "UsuarioCargoDepartamento" ("DepartamentoId", "DepartamentoCodigo");

SELECT setval(
    pg_get_serial_sequence('"Modulos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Modulos") + 1,
        nextval(pg_get_serial_sequence('"Modulos"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260623025316_InitialAtronPostgreSql', '6.0.32');

COMMIT;

