using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    public partial class CriandoCadastroBasicoEmpresa : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS ""SolicitacoesEmpresa"";
                DROP TABLE IF EXISTS ""UsuariosEmpresas"";

                DELETE FROM ""PerfilDeAcessoModulos""
                WHERE ""ModuloId"" IN (
                    SELECT ""Id"" FROM ""Modulos"" WHERE ""Codigo"" = 'EMP'
                );

                DELETE FROM ""Modulos"" WHERE ""Codigo"" = 'EMP';

                CREATE TABLE IF NOT EXISTS ""Empresas"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Codigo"" character varying(25) NOT NULL,
                    ""NomeFantasia"" character varying(150) NOT NULL,
                    ""Endereco"" character varying(200) NOT NULL,
                    ""Numero"" character varying(20) NOT NULL,
                    ""Email"" character varying(254) NOT NULL,
                    ""Status"" integer NOT NULL,
                    CONSTRAINT ""PK_Empresas"" PRIMARY KEY (""Id"")
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Empresas_Codigo""
                    ON ""Empresas"" (""Codigo"");

                DELETE FROM ""__EFMigrationsHistory""
                WHERE ""MigrationId"" IN (
                    '20260827222523_CriandoEmpresasEVinculosUsuarios',
                    '20260827230436_ModelandoEnderecoEmpresa',
                    '20260827235559_IncluindoModuloEmpresa',
                    '20260828010334_CriandoSolicitacoesEmpresa'
                );
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Empresas");
        }
    }
}
