CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AppRole" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NULL,
    "NormalizedName" character varying(50) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AppRole" PRIMARY KEY ("Id")
);

CREATE TABLE "AppUser" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RefreshToken" character varying(1000) NULL,
    "RefreshTokenExpireTime" timestamp without time zone NULL,
    "UserName" character varying(50) NOT NULL,
    "NormalizedUserName" character varying(50) NULL,
    "Email" character varying(60) NOT NULL,
    "NormalizedEmail" character varying(60) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" character varying(450) NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" character varying(25) NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AppUser" PRIMARY KEY ("Id")
);

CREATE TABLE "Departamentos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Descricao" character varying(50) NOT NULL,
    CONSTRAINT "PK_Departamentos" PRIMARY KEY ("Id", "Codigo")
);

CREATE TABLE "Modulos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Descricao" character varying(100) NOT NULL,
    CONSTRAINT "PK_Modulos" PRIMARY KEY ("Id", "Codigo")
);

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Nome" character varying(25) NOT NULL,
    "Sobrenome" character varying(50) NOT NULL,
    "Email" character varying(50) NOT NULL,
    "DataNascimento" timestamp without time zone NULL,
    "SalarioAtual" integer NULL,
    "Inativo" boolean NOT NULL DEFAULT FALSE,
    "CodigoReativacao" character varying(6) NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id", "Codigo")
);

CREATE TABLE "AppRoleClaim" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" character varying(128) NULL,
    "ClaimValue" character varying(128) NULL,
    CONSTRAINT "PK_AppRoleClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AppRoleClaim_AppRole_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AppRole" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AppUserClaim" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" character varying(50) NULL,
    "ClaimValue" character varying(50) NULL,
    CONSTRAINT "PK_AppUserClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AppUserClaim_AppUser_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AppUserLogin" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AppUserLogin" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AppUserLogin_AppUser_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AppUserRole" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AppUserRole" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AppUserRole_AppRole_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AppRole" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AppUserRole_AppUser_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AppUserToken" (
    "UserId" integer NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Value" character varying(450) NULL,
    CONSTRAINT "PK_AppUserToken" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AppUserToken_AppUser_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUser" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Cargos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Descricao" character varying(50) NOT NULL,
    "DepartamentoId" integer NOT NULL,
    "DepartamentoCodigo" character varying(10) NULL,
    CONSTRAINT "PK_Cargos" PRIMARY KEY ("Id", "Codigo"),
    CONSTRAINT "FK_Cargos_Departamentos_DepartamentoId_DepartamentoCodigo" FOREIGN KEY ("DepartamentoId", "DepartamentoCodigo") REFERENCES "Departamentos" ("Id", "Codigo")
);

CREATE TABLE "PerfisDeAcesso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Descricao" character varying(50) NOT NULL,
    "UsuarioId" integer NULL,
    "UsuarioCodigo" character varying(10) NULL,
    CONSTRAINT "PK_PerfisDeAcesso" PRIMARY KEY ("Id", "Codigo"),
    CONSTRAINT "FK_PerfisDeAcesso_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo")
);

CREATE TABLE "Salarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "UsuarioCodigo" character varying(10) NOT NULL,
    "SalarioMensal" integer NOT NULL,
    "Ano" character varying(4) NOT NULL,
    "MesId" integer NOT NULL,
    CONSTRAINT "PK_Salarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Salarios_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE CASCADE
);

CREATE TABLE "Tarefas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "UsuarioCodigo" character varying(10) NULL,
    "Titulo" character varying(50) NOT NULL,
    "Conteudo" character varying(2500) NULL,
    "DataInicial" timestamp without time zone NOT NULL,
    "DataFinal" timestamp without time zone NOT NULL,
    "TarefaEstadoId" integer NOT NULL,
    CONSTRAINT "PK_Tarefas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tarefas_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo")
);

CREATE TABLE "UsuarioCargoDepartamento" (
    "UsuarioId" integer NOT NULL,
    "UsuarioCodigo" character varying(10) NOT NULL,
    "CargoId" integer NOT NULL,
    "CargoCodigo" character varying(10) NOT NULL,
    "DepartamentoId" integer NOT NULL,
    "DepartamentoCodigo" character varying(10) NOT NULL,
    CONSTRAINT "PK_UsuarioCargoDepartamento" PRIMARY KEY ("UsuarioId", "UsuarioCodigo", "CargoId", "CargoCodigo", "DepartamentoId", "DepartamentoCodigo"),
    CONSTRAINT "FK_UsuarioCargoDepartamento_Cargos_CargoId_CargoCodigo" FOREIGN KEY ("CargoId", "CargoCodigo") REFERENCES "Cargos" ("Id", "Codigo") ON DELETE CASCADE,
    CONSTRAINT "FK_UsuarioCargoDepartamento_Departamentos_DepartamentoId_Depar~" FOREIGN KEY ("DepartamentoId", "DepartamentoCodigo") REFERENCES "Departamentos" ("Id", "Codigo") ON DELETE CASCADE,
    CONSTRAINT "FK_UsuarioCargoDepartamento_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE CASCADE
);

CREATE TABLE "PerfilDeAcessoModulos" (
    "PerfilDeAcessoId" integer NOT NULL,
    "PerfilDeAcessoCodigo" character varying(10) NOT NULL,
    "ModuloId" integer NOT NULL,
    "ModuloCodigo" character varying(10) NOT NULL,
    CONSTRAINT "PK_PerfilDeAcessoModulos" PRIMARY KEY ("PerfilDeAcessoId", "PerfilDeAcessoCodigo", "ModuloId", "ModuloCodigo"),
    CONSTRAINT "FK_PerfilDeAcessoModulos_Modulos_ModuloId_ModuloCodigo" FOREIGN KEY ("ModuloId", "ModuloCodigo") REFERENCES "Modulos" ("Id", "Codigo") ON DELETE CASCADE,
    CONSTRAINT "FK_PerfilDeAcessoModulos_PerfisDeAcesso_PerfilDeAcessoId_Perfi~" FOREIGN KEY ("PerfilDeAcessoId", "PerfilDeAcessoCodigo") REFERENCES "PerfisDeAcesso" ("Id", "Codigo") ON DELETE CASCADE
);

CREATE TABLE "PerfilDeAcessoUsuarios" (
    "PerfilDeAcessoId" integer NOT NULL,
    "PerfilDeAcessoCodigo" character varying(10) NOT NULL,
    "UsuarioId" integer NOT NULL,
    "UsuarioCodigo" character varying(10) NOT NULL,
    CONSTRAINT "PK_PerfilDeAcessoUsuarios" PRIMARY KEY ("PerfilDeAcessoId", "PerfilDeAcessoCodigo", "UsuarioId", "UsuarioCodigo"),
    CONSTRAINT "FK_PerfilDeAcessoUsuarios_PerfisDeAcesso_PerfilDeAcessoId_Perf~" FOREIGN KEY ("PerfilDeAcessoId", "PerfilDeAcessoCodigo") REFERENCES "PerfisDeAcesso" ("Id", "Codigo") ON DELETE CASCADE,
    CONSTRAINT "FK_PerfilDeAcessoUsuarios_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE CASCADE
);

INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('DPT', 1, 'Departamentos');
INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('CRG', 2, 'Cargos');
INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('USR', 3, 'Usuários');
INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('TAR', 4, 'Tarefas');
INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('SAL', 5, 'Salários');
INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('PAC', 6, 'Políticas e Acessos');

CREATE UNIQUE INDEX "RoleNameIndex" ON "AppRole" ("NormalizedName");

CREATE INDEX "IX_AppRoleClaim_RoleId" ON "AppRoleClaim" ("RoleId");

CREATE INDEX "EmailIndex" ON "AppUser" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AppUser" ("NormalizedUserName");

CREATE INDEX "IX_AppUserClaim_UserId" ON "AppUserClaim" ("UserId");

CREATE INDEX "IX_AppUserLogin_UserId" ON "AppUserLogin" ("UserId");

CREATE INDEX "IX_AppUserRole_RoleId" ON "AppUserRole" ("RoleId");

CREATE INDEX "IX_Cargos_DepartamentoId_DepartamentoCodigo" ON "Cargos" ("DepartamentoId", "DepartamentoCodigo");

CREATE INDEX "IX_PerfilDeAcessoModulos_ModuloId_ModuloCodigo" ON "PerfilDeAcessoModulos" ("ModuloId", "ModuloCodigo");

CREATE INDEX "IX_PerfilDeAcessoUsuarios_UsuarioId_UsuarioCodigo" ON "PerfilDeAcessoUsuarios" ("UsuarioId", "UsuarioCodigo");

CREATE INDEX "IX_PerfisDeAcesso_UsuarioId_UsuarioCodigo" ON "PerfisDeAcesso" ("UsuarioId", "UsuarioCodigo");

CREATE UNIQUE INDEX "IX_Salarios_UsuarioId_UsuarioCodigo" ON "Salarios" ("UsuarioId", "UsuarioCodigo");

CREATE INDEX "IX_Tarefas_UsuarioId_UsuarioCodigo" ON "Tarefas" ("UsuarioId", "UsuarioCodigo");

CREATE INDEX "IX_UsuarioCargoDepartamento_CargoId_CargoCodigo" ON "UsuarioCargoDepartamento" ("CargoId", "CargoCodigo");

CREATE INDEX "IX_UsuarioCargoDepartamento_DepartamentoId_DepartamentoCodigo" ON "UsuarioCargoDepartamento" ("DepartamentoId", "DepartamentoCodigo");

SELECT setval(
    pg_get_serial_sequence('"Modulos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Modulos") + 1,
        nextval(pg_get_serial_sequence('"Modulos"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260623025316_InitialAtronPostgreSql', '6.0.32');

COMMIT;

START TRANSACTION;

ALTER TABLE "Usuarios" ADD "ReceberNotificacaoTarefaPorEmail" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260702001246_IncluindoPreferenciaNotificacaoTarefaUsuario', '6.0.32');

COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM "Modulos" WHERE "Id" = 6 AND "Codigo" = 'PERF') THEN
        UPDATE "Modulos" SET "Descricao" = 'Perfil de acesso' WHERE "Id" = 6 AND "Codigo" = 'PERF';
    ELSIF EXISTS (SELECT 1 FROM "Modulos" WHERE "Id" = 6 AND "Codigo" = 'PAC') THEN
        UPDATE "Modulos" SET "Codigo" = 'PERF', "Descricao" = 'Perfil de acesso' WHERE "Id" = 6 AND "Codigo" = 'PAC';
    ELSE
        INSERT INTO "Modulos" ("Codigo", "Id", "Descricao") VALUES ('PERF', 6, 'Perfil de acesso');
    END IF;

    IF EXISTS (SELECT 1 FROM "Modulos" WHERE "Id" = 10 AND "Codigo" = 'RPERFUSR') THEN
        UPDATE "Modulos" SET "Descricao" = 'Relacionamento de perfil e usuários' WHERE "Id" = 10 AND "Codigo" = 'RPERFUSR';
    ELSE
        INSERT INTO "Modulos" ("Codigo", "Id", "Descricao") VALUES ('RPERFUSR', 10, 'Relacionamento de perfil e usuários');
    END IF;
END $$;


CREATE TABLE "TarefaEstados" (
    "Id" integer NOT NULL,
    "Descricao" character varying(100) NOT NULL,
    CONSTRAINT "PK_TarefaEstados" PRIMARY KEY ("Id")
);

INSERT INTO "TarefaEstados" ("Id", "Descricao")
VALUES (1, 'Em atividade');
INSERT INTO "TarefaEstados" ("Id", "Descricao")
VALUES (2, 'Pendente de aprovação');
INSERT INTO "TarefaEstados" ("Id", "Descricao")
VALUES (3, 'Entregue');
INSERT INTO "TarefaEstados" ("Id", "Descricao")
VALUES (4, 'Finalizada');
INSERT INTO "TarefaEstados" ("Id", "Descricao")
VALUES (5, 'Iniciada');

CREATE INDEX "IX_Tarefas_TarefaEstadoId" ON "Tarefas" ("TarefaEstadoId");

ALTER TABLE "Tarefas" ADD CONSTRAINT "FK_Tarefas_TarefaEstados_TarefaEstadoId" FOREIGN KEY ("TarefaEstadoId") REFERENCES "TarefaEstados" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260702152143_AlinhandoModulosETarefaEstados', '6.0.32');

COMMIT;

START TRANSACTION;

DROP TABLE "Salarios";

DELETE FROM "PerfilDeAcessoModulos" WHERE "ModuloId" = 5 AND "ModuloCodigo" = 'SAL'

DELETE FROM "Modulos"
WHERE "Codigo" = 'SAL' AND "Id" = 5;

ALTER TABLE "Usuarios" DROP COLUMN "SalarioAtual";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703134221_RemovendoModuloSalarios', '6.0.32');

COMMIT;

START TRANSACTION;

INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('PLC', 11, 'Planejamento de Custos');

SELECT setval(
    pg_get_serial_sequence('"Modulos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Modulos") + 1,
        nextval(pg_get_serial_sequence('"Modulos"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703134819_IncluindoModuloPlanejamentoCustos', '6.0.32');

COMMIT;

START TRANSACTION;

CREATE TABLE "PlanejamentosCusto" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" character varying(10) NOT NULL,
    "Descricao" character varying(100) NOT NULL,
    "Ano" integer NOT NULL,
    "ValorMinimo" numeric(18,2) NOT NULL,
    "ValorTeto" numeric(18,2) NOT NULL,
    "ApenasDepartamento" boolean NOT NULL,
    "DepartamentoId" integer NOT NULL,
    "DepartamentoCodigo" character varying(10) NOT NULL,
    CONSTRAINT "PK_PlanejamentosCusto" PRIMARY KEY ("Id", "Codigo"),
    CONSTRAINT "FK_PlanejamentosCusto_Departamentos_DepartamentoId_Departament~" FOREIGN KEY ("DepartamentoId", "DepartamentoCodigo") REFERENCES "Departamentos" ("Id", "Codigo") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_PlanejamentosCusto_DepartamentoId_DepartamentoCodigo_Ano" ON "PlanejamentosCusto" ("DepartamentoId", "DepartamentoCodigo", "Ano");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703144028_CriandoPlanejamentoCusto', '6.0.32');

COMMIT;

START TRANSACTION;

CREATE TABLE "PlanejamentosCustoCargo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlanejamentoCustoId" integer NOT NULL,
    "PlanejamentoCustoCodigo" character varying(10) NOT NULL,
    "CargoId" integer NOT NULL,
    "CargoCodigo" character varying(10) NOT NULL,
    "Detalhado" boolean NOT NULL,
    "ValorMinimo" numeric(18,2) NULL,
    "ValorTeto" numeric(18,2) NULL,
    CONSTRAINT "PK_PlanejamentosCustoCargo" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlanejamentosCustoCargo_Cargos_CargoId_CargoCodigo" FOREIGN KEY ("CargoId", "CargoCodigo") REFERENCES "Cargos" ("Id", "Codigo") ON DELETE RESTRICT,
    CONSTRAINT "FK_PlanejamentosCustoCargo_PlanejamentosCusto_PlanejamentoCust~" FOREIGN KEY ("PlanejamentoCustoId", "PlanejamentoCustoCodigo") REFERENCES "PlanejamentosCusto" ("Id", "Codigo") ON DELETE CASCADE
);

CREATE INDEX "IX_PlanejamentosCustoCargo_CargoId_CargoCodigo" ON "PlanejamentosCustoCargo" ("CargoId", "CargoCodigo");

CREATE UNIQUE INDEX "IX_PlanejamentosCustoCargo_PlanejamentoCustoId_PlanejamentoCus~" ON "PlanejamentosCustoCargo" ("PlanejamentoCustoId", "PlanejamentoCustoCodigo", "CargoId", "CargoCodigo");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703154504_CriandoDetalhesCargoPlanejamentoCusto', '6.0.32');

COMMIT;

START TRANSACTION;

ALTER TABLE "Usuarios" ADD "GestorImediatoCodigo" character varying(10) NULL;

ALTER TABLE "Usuarios" ADD "GestorImediatoId" integer NULL;

ALTER TABLE "Departamentos" ADD "GestorDepartamentoCodigo" character varying(10) NULL;

ALTER TABLE "Departamentos" ADD "GestorDepartamentoId" integer NULL;

CREATE INDEX "IX_Usuarios_GestorImediatoId_GestorImediatoCodigo" ON "Usuarios" ("GestorImediatoId", "GestorImediatoCodigo");

CREATE INDEX "IX_Departamentos_GestorDepartamentoId_GestorDepartamentoCodigo" ON "Departamentos" ("GestorDepartamentoId", "GestorDepartamentoCodigo");

ALTER TABLE "Departamentos" ADD CONSTRAINT "FK_Departamentos_Usuarios_GestorDepartamentoId_GestorDepartame~" FOREIGN KEY ("GestorDepartamentoId", "GestorDepartamentoCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE RESTRICT;

ALTER TABLE "Usuarios" ADD CONSTRAINT "FK_Usuarios_Usuarios_GestorImediatoId_GestorImediatoCodigo" FOREIGN KEY ("GestorImediatoId", "GestorImediatoCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260706180517_IncluindoGestoresUsuarioDepartamento', '6.0.32');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tarefas" DROP CONSTRAINT "FK_Tarefas_Usuarios_UsuarioId_UsuarioCodigo";

ALTER TABLE "Tarefas" ALTER COLUMN "UsuarioId" DROP NOT NULL;

ALTER TABLE "Tarefas" ADD "CargoCodigo" character varying(10) NULL;

ALTER TABLE "Tarefas" ADD "CargoId" integer NULL;

ALTER TABLE "Tarefas" ADD "DepartamentoCodigo" character varying(10) NULL;

ALTER TABLE "Tarefas" ADD "DepartamentoId" integer NULL;

ALTER TABLE "Tarefas" ADD "DestinoInicial" integer NOT NULL DEFAULT 1;

ALTER TABLE "Tarefas" ADD "Identificador" integer NULL;

UPDATE "Tarefas" SET "Identificador" = "Id" WHERE "Identificador" IS NULL;

CREATE INDEX "IX_Tarefas_CargoId_CargoCodigo" ON "Tarefas" ("CargoId", "CargoCodigo");

CREATE INDEX "IX_Tarefas_DepartamentoId_DepartamentoCodigo" ON "Tarefas" ("DepartamentoId", "DepartamentoCodigo");

CREATE INDEX "IX_Tarefas_Identificador" ON "Tarefas" ("Identificador");

ALTER TABLE "Tarefas" ADD CONSTRAINT "FK_Tarefas_Cargos_CargoId_CargoCodigo" FOREIGN KEY ("CargoId", "CargoCodigo") REFERENCES "Cargos" ("Id", "Codigo") ON DELETE RESTRICT;

ALTER TABLE "Tarefas" ADD CONSTRAINT "FK_Tarefas_Departamentos_DepartamentoId_DepartamentoCodigo" FOREIGN KEY ("DepartamentoId", "DepartamentoCodigo") REFERENCES "Departamentos" ("Id", "Codigo") ON DELETE RESTRICT;

ALTER TABLE "Tarefas" ADD CONSTRAINT "FK_Tarefas_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260706182203_RemodelandoModeloTarefaDestinoEscopo', '6.0.32');

COMMIT;

START TRANSACTION;

ALTER TABLE "Tarefas" ADD "ExigeAprovacaoParaObter" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "SolicitacoesObtencaoTarefa" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TarefaId" integer NOT NULL,
    "SolicitanteId" integer NOT NULL,
    "SolicitanteCodigo" character varying(10) NOT NULL,
    "AprovadorId" integer NOT NULL,
    "AprovadorCodigo" character varying(10) NOT NULL,
    "Status" integer NOT NULL,
    "DataSolicitacao" timestamp without time zone NOT NULL,
    "DataDecisao" timestamp without time zone NULL,
    CONSTRAINT "PK_SolicitacoesObtencaoTarefa" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SolicitacoesObtencaoTarefa_Tarefas_TarefaId" FOREIGN KEY ("TarefaId") REFERENCES "Tarefas" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SolicitacoesObtencaoTarefa_Usuarios_AprovadorId_AprovadorCo~" FOREIGN KEY ("AprovadorId", "AprovadorCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE RESTRICT,
    CONSTRAINT "FK_SolicitacoesObtencaoTarefa_Usuarios_SolicitanteId_Solicitan~" FOREIGN KEY ("SolicitanteId", "SolicitanteCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE RESTRICT
);

CREATE INDEX "IX_SolicitacoesObtencaoTarefa_AprovadorId_AprovadorCodigo_Stat~" ON "SolicitacoesObtencaoTarefa" ("AprovadorId", "AprovadorCodigo", "Status");

CREATE INDEX "IX_SolicitacoesObtencaoTarefa_SolicitanteId_SolicitanteCodigo" ON "SolicitacoesObtencaoTarefa" ("SolicitanteId", "SolicitanteCodigo");

CREATE INDEX "IX_SolicitacoesObtencaoTarefa_TarefaId_Status" ON "SolicitacoesObtencaoTarefa" ("TarefaId", "Status");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260706190711_IncluindoSolicitacoesObtencaoTarefa', '6.0.32');

COMMIT;

START TRANSACTION;

CREATE TABLE "NotificacoesInternas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "UsuarioCodigo" character varying(10) NOT NULL,
    "Titulo" character varying(120) NOT NULL,
    "Mensagem" character varying(500) NOT NULL,
    "Modulo" character varying(50) NOT NULL,
    "TipoEvento" character varying(80) NOT NULL,
    "UrlDestino" character varying(250) NULL,
    "TarefaId" integer NULL,
    "Lida" boolean NOT NULL DEFAULT FALSE,
    "DataCriacao" timestamp without time zone NOT NULL,
    "DataLeitura" timestamp without time zone NULL,
    CONSTRAINT "PK_NotificacoesInternas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NotificacoesInternas_Tarefas_TarefaId" FOREIGN KEY ("TarefaId") REFERENCES "Tarefas" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_NotificacoesInternas_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE RESTRICT
);

CREATE INDEX "IX_NotificacoesInternas_TarefaId" ON "NotificacoesInternas" ("TarefaId");

CREATE INDEX "IX_NotificacoesInternas_UsuarioId_UsuarioCodigo_Lida" ON "NotificacoesInternas" ("UsuarioId", "UsuarioCodigo", "Lida");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260706193844_CriandoNotificacoesInternas', '6.0.32');

COMMIT;

START TRANSACTION;

ALTER TABLE "Usuarios" ADD "ReceberNotificacaoInternaTarefa" boolean NOT NULL DEFAULT TRUE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260708120000_IncluindoPreferenciaNotificacaoInternaTarefa', '6.0.32');

COMMIT;

START TRANSACTION;

ALTER TABLE "Usuarios" ADD "EmailConfirmado" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260710015251_IncluindoConfirmacaoEmailUsuario', '6.0.32');

COMMIT;

START TRANSACTION;

CREATE TABLE "ConfirmacoesEmail" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioCodigo" character varying(10) NOT NULL,
    "IdentificadorHash" character varying(128) NOT NULL,
    "CriadoEm" timestamp without time zone NOT NULL,
    "ExpiraEm" timestamp without time zone NOT NULL,
    "ConfirmadoEm" timestamp without time zone NULL,
    CONSTRAINT "PK_ConfirmacoesEmail" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_ConfirmacoesEmail_UsuarioCodigo_ExpiraEm_ConfirmadoEm" ON "ConfirmacoesEmail" ("UsuarioCodigo", "ExpiraEm", "ConfirmadoEm");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260710020706_IncluindoTabelaConfirmacaoEmail', '6.0.32');

COMMIT;

START TRANSACTION;

DROP TABLE IF EXISTS "NotificacoesInternas";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260720200000_RemoverNotificacoesInternasLegadas', '6.0.32');

COMMIT;

START TRANSACTION;

CREATE TABLE "TarefaMovimentacoes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TarefaId" integer NOT NULL,
    "Tipo" integer NOT NULL,
    "Descricao" character varying(1500) NOT NULL,
    "ResponsavelCodigo" character varying(10) NOT NULL,
    "ResponsavelNome" character varying(200) NOT NULL,
    "DataOcorrencia" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_TarefaMovimentacoes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TarefaMovimentacoes_Tarefas_TarefaId" FOREIGN KEY ("TarefaId") REFERENCES "Tarefas" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TarefaMovimentacoes_TarefaId_DataOcorrencia" ON "TarefaMovimentacoes" ("TarefaId", "DataOcorrencia");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260726184409_IncluindoHistoricoMovimentacoesTarefa', '6.0.32');

COMMIT;

START TRANSACTION;

INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('CAT', 12, 'Categorias');

SELECT setval(
    pg_get_serial_sequence('"Modulos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Modulos") + 1,
        nextval(pg_get_serial_sequence('"Modulos"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260727005918_IncluindoModuloCategoria', '6.0.32');

COMMIT;

START TRANSACTION;

ALTER TABLE "ConfirmacoesEmail" ADD "TentativasFalhas" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260804140612_LimitandoTentativasConfirmacaoEmail', '6.0.32');

COMMIT;

START TRANSACTION;

UPDATE "AppUser" SET "RefreshToken" = NULL, "RefreshTokenExpireTime" = NULL;

ALTER TABLE "AppUser" ALTER COLUMN "RefreshToken" TYPE character varying(64);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260804144148_ProtegendoRefreshToken', '6.0.32');

COMMIT;

START TRANSACTION;

INSERT INTO "Modulos" ("Codigo", "Id", "Descricao")
VALUES ('PRD', 13, 'Produtos');

SELECT setval(
    pg_get_serial_sequence('"Modulos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Modulos") + 1,
        nextval(pg_get_serial_sequence('"Modulos"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260824235854_IncluindoModuloProduto', '6.0.32');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_Tarefas_Identificador";

ALTER TABLE "Tarefas" DROP COLUMN "Identificador";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260825031916_RemovendoIdentificadorTarefa', '6.0.32');

COMMIT;

START TRANSACTION;

CREATE TABLE "MembrosWorkspace" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkspaceId" integer NOT NULL,
    "WorkspaceCodigo" character varying(10) NOT NULL,
    "UsuarioCodigo" character varying(10) NOT NULL,
    "UsuarioId" integer NULL,
    CONSTRAINT "PK_MembrosWorkspace" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MembrosWorkspace_Workspaces_WorkspaceId_WorkspaceCodigo" FOREIGN KEY ("WorkspaceId", "WorkspaceCodigo") REFERENCES "Workspaces" ("Id", "Codigo") ON DELETE CASCADE,
    CONSTRAINT "FK_MembrosWorkspace_Usuarios_UsuarioId_UsuarioCodigo" FOREIGN KEY ("UsuarioId", "UsuarioCodigo") REFERENCES "Usuarios" ("Id", "Codigo")
);

CREATE INDEX "IX_MembrosWorkspace_UsuarioId_UsuarioCodigo" ON "MembrosWorkspace" ("UsuarioId", "UsuarioCodigo");

CREATE INDEX "IX_MembrosWorkspace_WorkspaceId_WorkspaceCodigo" ON "MembrosWorkspace" ("WorkspaceId", "WorkspaceCodigo");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260912024914_ConfiguracaoMembrosWorkspace', '6.0.32');

COMMIT;

START TRANSACTION;

ALTER TABLE "Usuarios" DROP CONSTRAINT "FK_Usuarios_Workspaces_WorkspaceId_WorkspaceCodigo";

ALTER TABLE "Workspaces" DROP CONSTRAINT "FK_Workspaces_Usuarios_ResponsavelCodigo_ResponsavelEmail";

DROP INDEX "IX_Workspaces_ResponsavelCodigo_ResponsavelEmail";

ALTER TABLE "Usuarios" DROP CONSTRAINT "AK_Usuarios_Codigo_Email";

DROP INDEX "IX_Usuarios_WorkspaceId_WorkspaceCodigo";

ALTER TABLE "Usuarios" DROP COLUMN "WorkspaceCodigo";

ALTER TABLE "Usuarios" DROP COLUMN "WorkspaceId";

ALTER TABLE "Workspaces" ALTER COLUMN "ResponsavelEmail" TYPE character varying(20);
UPDATE "Workspaces" SET "ResponsavelEmail" = '' WHERE "ResponsavelEmail" IS NULL;
ALTER TABLE "Workspaces" ALTER COLUMN "ResponsavelEmail" SET NOT NULL;
ALTER TABLE "Workspaces" ALTER COLUMN "ResponsavelEmail" SET DEFAULT '';

ALTER TABLE "Workspaces" ALTER COLUMN "Codigo" TYPE character varying(10);

ALTER TABLE "Workspaces" ADD "ResponsavelId" integer NULL;

CREATE UNIQUE INDEX "IX_Workspaces_ResponsavelId_ResponsavelCodigo" ON "Workspaces" ("ResponsavelId", "ResponsavelCodigo");

ALTER TABLE "Workspaces" ADD CONSTRAINT "FK_Workspaces_Usuarios_ResponsavelId_ResponsavelCodigo" FOREIGN KEY ("ResponsavelId", "ResponsavelCodigo") REFERENCES "Usuarios" ("Id", "Codigo") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260914000824_AddWorkspaceResponsavelFk', '6.0.32');

COMMIT;

