// <auto-generated />
using System;
using AtronStock.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtronStock.Infrastructure.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20261001192516_RemoveLegacyStockEntities")]
    partial class RemoveLegacyStockEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtronStock.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("Ativo");

                    b.HasKey("Id");

                    b.HasAlternateKey("Codigo");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.LoteProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("LotesProdutos");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ProcessamentoProdutoLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LoteProdutoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReservaExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReservadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pendente");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TokenReserva")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteProdutoId")
                        .IsUnique();

                    b.HasIndex("Status", "Id");

                    b.HasIndex("Status", "ReservaExpiraEm", "Id");

                    b.ToTable("ProcessamentosProdutosLote");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime?>("DataAquisicao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataEfetivaBaixa")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DescricaoComplementar")
                        .HasColumnType("text");

                    b.Property<int?>("LoteProdutoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Ativo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("LoteProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ProdutoCategoria", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoriaCodigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("ProdutoCodigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("ProdutoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("ProdutoCategorias");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ProcessamentoProdutoLote", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.LoteProduto", "LoteProduto")
                        .WithMany()
                        .HasForeignKey("LoteProdutoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("AtronStock.Domain.ValueObjects.ResultadoProcessamentoProdutoLote", "Resultado", b1 =>
                        {
                            b1.Property<int>("ProcessamentoProdutoLoteId")
                                .HasColumnType("integer");

                            b1.Property<string>("Erro")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Erro");

                            b1.Property<int>("QuantidadeProcessada")
                                .HasColumnType("integer")
                                .HasColumnName("QuantidadeProcessada");

                            b1.HasKey("ProcessamentoProdutoLoteId");

                            b1.ToTable("ProcessamentosProdutosLote");

                            b1.WithOwner()
                                .HasForeignKey("ProcessamentoProdutoLoteId");
                        });

                    b.OwnsOne("AtronStock.Domain.ValueObjects.SolicitacaoGeracaoProdutosLote", "Solicitacao", b1 =>
                        {
                            b1.Property<int>("ProcessamentoProdutoLoteId")
                                .HasColumnType("integer");

                            b1.Property<string>("CategoriaCodigos")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CategoriaCodigos");

                            b1.Property<string>("CodigoBase")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)")
                                .HasColumnName("CodigoBase");

                            b1.Property<DateTime>("DataAquisicao")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("DataAquisicao");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Descricao");

                            b1.Property<string>("DescricaoComplementar")
                                .HasColumnType("text")
                                .HasColumnName("DescricaoComplementar");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PrecoUnitario");

                            b1.Property<int>("QuantidadeSolicitada")
                                .HasColumnType("integer")
                                .HasColumnName("QuantidadeSolicitada");

                            b1.Property<string>("SolicitanteCodigo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("SolicitanteCodigo");

                            b1.HasKey("ProcessamentoProdutoLoteId");

                            b1.ToTable("ProcessamentosProdutosLote");

                            b1.WithOwner()
                                .HasForeignKey("ProcessamentoProdutoLoteId");
                        });

                    b.Navigation("LoteProduto");

                    b.Navigation("Resultado")
                        .IsRequired();

                    b.Navigation("Solicitacao")
                        .IsRequired();
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Produto", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.LoteProduto", "LoteProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("LoteProdutoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoteProduto");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ProdutoCategoria", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtronStock.Domain.Entities.Produto", "Produto")
                        .WithMany("Categorias")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.LoteProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
