// <auto-generated />
using System;
using AtronStock.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtronStock.Infrastructure.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260830211946_PersistindoEnumsComoTexto")]
    partial class PersistindoEnumsComoTexto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtronStock.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Ativo");

                    b.HasKey("Id");

                    b.HasAlternateKey("Codigo");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("CPF")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FornecedorCodigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Entradas", (string)null);
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId")
                        .IsUnique();

                    b.ToTable("Estoques", (string)null);
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Fornecedores", (string)null);
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ItemEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntradaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProdutoCodigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensEntrada", (string)null);
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProdutoCodigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensVenda", (string)null);
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.LoteProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("LotesProdutos");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EstoqueId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Origem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("TransacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueId");

                    b.ToTable("MovimentacoesEstoque", (string)null);
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ProcessamentoProdutoLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LoteProdutoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReservaExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReservadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pendente");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TokenReserva")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteProdutoId")
                        .IsUnique();

                    b.HasIndex("Status", "Id");

                    b.HasIndex("Status", "ReservaExpiraEm", "Id");

                    b.ToTable("ProcessamentosProdutosLote");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime?>("DataAquisicao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataEfetivaBaixa")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DescricaoComplementar")
                        .HasColumnType("text");

                    b.Property<int?>("LoteProdutoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Ativo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("LoteProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ProdutoCategoria", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoriaCodigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("ProdutoCodigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("ProdutoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("ProdutoCategorias");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteCodigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Removido")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RemovidoEm")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("AtronStock.Domain.ValueObjects.EnderecoVO", "Endereco", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("integer");

                            b1.Property<string>("CEP")
                                .HasMaxLength(9)
                                .HasColumnType("character varying(9)");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Numero")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("UF")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Entrada", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.Produto", "Produto")
                        .WithOne()
                        .HasForeignKey("AtronStock.Domain.Entities.Estoque", "ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Fornecedor", b =>
                {
                    b.OwnsOne("AtronStock.Domain.ValueObjects.EnderecoVO", "Endereco", b1 =>
                        {
                            b1.Property<int>("FornecedorId")
                                .HasColumnType("integer");

                            b1.Property<string>("CEP")
                                .HasMaxLength(9)
                                .HasColumnType("character varying(9)");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Numero")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("UF")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.HasKey("FornecedorId");

                            b1.ToTable("Fornecedores");

                            b1.WithOwner()
                                .HasForeignKey("FornecedorId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ItemEntrada", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.Entrada", "Entrada")
                        .WithMany("Itens")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtronStock.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entrada");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ItemVenda", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtronStock.Domain.Entities.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.Estoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estoque");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ProcessamentoProdutoLote", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.LoteProduto", "LoteProduto")
                        .WithMany()
                        .HasForeignKey("LoteProdutoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("AtronStock.Domain.ValueObjects.ResultadoProcessamentoProdutoLote", "Resultado", b1 =>
                        {
                            b1.Property<int>("ProcessamentoProdutoLoteId")
                                .HasColumnType("integer");

                            b1.Property<string>("Erro")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Erro");

                            b1.Property<int>("QuantidadeProcessada")
                                .HasColumnType("integer")
                                .HasColumnName("QuantidadeProcessada");

                            b1.HasKey("ProcessamentoProdutoLoteId");

                            b1.ToTable("ProcessamentosProdutosLote");

                            b1.WithOwner()
                                .HasForeignKey("ProcessamentoProdutoLoteId");
                        });

                    b.OwnsOne("AtronStock.Domain.ValueObjects.SolicitacaoGeracaoProdutosLote", "Solicitacao", b1 =>
                        {
                            b1.Property<int>("ProcessamentoProdutoLoteId")
                                .HasColumnType("integer");

                            b1.Property<string>("CategoriaCodigos")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CategoriaCodigos");

                            b1.Property<string>("CodigoBase")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)")
                                .HasColumnName("CodigoBase");

                            b1.Property<DateTime>("DataAquisicao")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("DataAquisicao");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Descricao");

                            b1.Property<string>("DescricaoComplementar")
                                .HasColumnType("text")
                                .HasColumnName("DescricaoComplementar");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PrecoUnitario");

                            b1.Property<int>("QuantidadeSolicitada")
                                .HasColumnType("integer")
                                .HasColumnName("QuantidadeSolicitada");

                            b1.Property<string>("SolicitanteCodigo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("SolicitanteCodigo");

                            b1.HasKey("ProcessamentoProdutoLoteId");

                            b1.ToTable("ProcessamentosProdutosLote");

                            b1.WithOwner()
                                .HasForeignKey("ProcessamentoProdutoLoteId");
                        });

                    b.Navigation("LoteProduto");

                    b.Navigation("Resultado")
                        .IsRequired();

                    b.Navigation("Solicitacao")
                        .IsRequired();
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Produto", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.LoteProduto", "LoteProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("LoteProdutoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoteProduto");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.ProdutoCategoria", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtronStock.Domain.Entities.Produto", "Produto")
                        .WithMany("Categorias")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Venda", b =>
                {
                    b.HasOne("AtronStock.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Entrada", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.LoteProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("AtronStock.Domain.Entities.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
