### Registrar Fornecedor
POST {{HostAddress}}/api/fornecedor
Content-Type: application/json

{
  "codigo": "ATL",
  "nome": "Atalanta Logistics",
  "email": "atl@email.com",
  "telefone": "21970995342",
  "cnpj": "12458687000211"  
}

### Listar Fornecedores
GET {{HostAddress}}/api/fornecedor
Accept: application/json
