### Registra um novo usuário
POST {{$projectUrl}}/api/acesso/registrar
Content-Type: application/json
{
  "codigo": "DEW",
  "nome": "Dery",
  "sobrenome": "Dghit",
  "dataNascimento": "1990-06-15",  
  "email": "kalifor_dbel@hotmail.com",
  "senha": "!QAZ24wsx@#",
  "confirmaSenha": "!QAZ24wsx@#"
}

### Confirma o e-mail do usuário

POST {{$projectUrl}}/api/acesso/confirmarEmail
Content-Type: application/json
{
  "usuarioCodigo": "DEW",
  "token": "CfDJ8PJTg7FyAV9CujOiiXrPYNsWvSuowIiwNYWKAUSCQcecOJvEMRHJQQ0fl4CDIL6780bdHX9xEQOrFe3Iccrw+QRihqediz5ygkE2LGBtf2lG3PBJwO/toRk+Oyd5C41YKopITdPqEnFT44S6kBRxzxJVWekeBtrkG3Wvn8dzkdmu1zE32vHZyVN4z9LNxEVj3dwhh8RFR9qwE0/GozkbORY="
}

### Login para acessar
POST {{$projectUrl}}/api/acesso/login
Content-Type: application/json
{
  "usuarioCodigo": "Dew",
  "token": ""
}

