//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtronStock.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FornecedorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FornecedorResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtronStock.Application.Resources.FornecedorResource", typeof(FornecedorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor não encontrado..
        /// </summary>
        public static string Erro_FornecedorNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_FornecedorNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CEP deve conter exatamente 9 caracteres (ex: 12345-678)..
        /// </summary>
        public static string ErroCepTamanho {
            get {
                return ResourceManager.GetString("ErroCepTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Cidade excede o limite de 50 caracteres..
        /// </summary>
        public static string ErroCidadeTamanho {
            get {
                return ResourceManager.GetString("ErroCidadeTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formato do CNPJ é inválido..
        /// </summary>
        public static string ErroCnpjInvalido {
            get {
                return ResourceManager.GetString("ErroCnpjInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um fornecedor cadastrado com o código informado..
        /// </summary>
        public static string ErroCodigoFornecedorExistente {
            get {
                return ResourceManager.GetString("ErroCodigoFornecedorExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código do fornecedor não pode exceder 20 caracteres..
        /// </summary>
        public static string ErroCodigoLimiteMaximoDeCaractere {
            get {
                return ResourceManager.GetString("ErroCodigoLimiteMaximoDeCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código do fornecedor deve ter no mínimo 3 caracteres..
        /// </summary>
        public static string ErroCodigoLimiteMinimoDeCaractere {
            get {
                return ResourceManager.GetString("ErroCodigoLimiteMinimoDeCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código do fornecedor é obrigatório..
        /// </summary>
        public static string ErroCodigoObrigatorio {
            get {
                return ResourceManager.GetString("ErroCodigoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formato do Email é inválido..
        /// </summary>
        public static string ErroEmailInvalido {
            get {
                return ResourceManager.GetString("ErroEmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email é obrigatório..
        /// </summary>
        public static string ErroEmailObrigatorio {
            get {
                return ResourceManager.GetString("ErroEmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email excede o limite de 50 caracteres..
        /// </summary>
        public static string ErroEmailTamanho {
            get {
                return ResourceManager.GetString("ErroEmailTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor não encontrado..
        /// </summary>
        public static string ErroFornecedorNaoEncontrado {
            get {
                return ResourceManager.GetString("ErroFornecedorNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Logradouro excede o limite de 100 caracteres..
        /// </summary>
        public static string ErroLogradouroTamanho {
            get {
                return ResourceManager.GetString("ErroLogradouroTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do fornecedor tem um limite máximo de 100 caracteres..
        /// </summary>
        public static string ErroNomeLimiteMaximoDeCaractere {
            get {
                return ResourceManager.GetString("ErroNomeLimiteMaximoDeCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do fornecedor tem um limite mínimo de 5 caracteres.
        /// </summary>
        public static string ErroNomeLimiteMinimoDeCaractere {
            get {
                return ResourceManager.GetString("ErroNomeLimiteMinimoDeCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do fornecedor é obrigatório..
        /// </summary>
        public static string ErroNomeObrigatorio {
            get {
                return ResourceManager.GetString("ErroNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Número do endereço excede o limite de 10 caracteres..
        /// </summary>
        public static string ErroNumeroEnderecoTamanho {
            get {
                return ResourceManager.GetString("ErroNumeroEnderecoTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho do Telefone está inválido (min 8, max 15)..
        /// </summary>
        public static string ErroTelefoneTamanho {
            get {
                return ResourceManager.GetString("ErroTelefoneTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A UF deve conter exatamente 2 caracteres..
        /// </summary>
        public static string ErroUfTamanho {
            get {
                return ResourceManager.GetString("ErroUfTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor {0} criado com sucesso..
        /// </summary>
        public static string Mensagem_FornecedorCriado {
            get {
                return ResourceManager.GetString("Mensagem_FornecedorCriado", resourceCulture);
            }
        }
    }
}
