//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtronStock.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProdutoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProdutoResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtronStock.Application.Resources.ProdutoResource", typeof(ProdutoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto não encontrado..
        /// </summary>
        public static string Erro_ProdutoNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_ProdutoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código do produto não pode exceder 20 caracteres..
        /// </summary>
        public static string ErroCodigoLimiteMaximoDeCaractere {
            get {
                return ResourceManager.GetString("ErroCodigoLimiteMaximoDeCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código do produto deve ter no mínimo 3 caracteres..
        /// </summary>
        public static string ErroCodigoLimiteMinimoDeCaractere {
            get {
                return ResourceManager.GetString("ErroCodigoLimiteMinimoDeCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código do produto é obrigatório..
        /// </summary>
        public static string ErroCodigoObrigatorio {
            get {
                return ResourceManager.GetString("ErroCodigoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição do produto não pode exceder 100 caracteres..
        /// </summary>
        public static string ErroDescricaoLimiteMaximoCaractere {
            get {
                return ResourceManager.GetString("ErroDescricaoLimiteMaximoCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição do produto deve ter no mínimo 5 caracteres..
        /// </summary>
        public static string ErroDescricaoLimiteMinimoCaractere {
            get {
                return ResourceManager.GetString("ErroDescricaoLimiteMinimoCaractere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição do produto é obrigatória..
        /// </summary>
        public static string ErroDescricaoObrigatoria {
            get {
                return ResourceManager.GetString("ErroDescricaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao salvar o produto de código {0}..
        /// </summary>
        public static string ErroInesperadoDeGravacao {
            get {
                return ResourceManager.GetString("ErroInesperadoDeGravacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O preço do produto deve ser maior que zero..
        /// </summary>
        public static string ErroPrecoProduto {
            get {
                return ResourceManager.GetString("ErroPrecoProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um produto cadastrado com o código {0}..
        /// </summary>
        public static string ErroProdutoExistente {
            get {
                return ResourceManager.GetString("ErroProdutoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O produto deve estar associado a pelo menos uma categoria..
        /// </summary>
        public static string ErroProdutoSemCategoria {
            get {
                return ResourceManager.GetString("ErroProdutoSemCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O produto deve estar associado a pelo menos um fornecedor..
        /// </summary>
        public static string ErroProdutoSemFornecedor {
            get {
                return ResourceManager.GetString("ErroProdutoSemFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto {0} criado com sucesso..
        /// </summary>
        public static string Mensagem_ProdutoCriado {
            get {
                return ResourceManager.GetString("Mensagem_ProdutoCriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto {0} criado na data {1}..
        /// </summary>
        public static string MensagemProdutoCriado {
            get {
                return ResourceManager.GetString("MensagemProdutoCriado", resourceCulture);
            }
        }

        public static string ErroDataAquisicaoObrigatoria {
            get {
                return ResourceManager.GetString("ErroDataAquisicaoObrigatoria", resourceCulture);
            }
        }

        public static string ErroCategoriaInvalidaOuInativa {
            get {
                return ResourceManager.GetString("ErroCategoriaInvalidaOuInativa", resourceCulture);
            }
        }

        public static string ErroProdutoNaoEncontrado {
            get {
                return ResourceManager.GetString("ErroProdutoNaoEncontrado", resourceCulture);
            }
        }

        public static string ErroInesperadoAtualizar {
            get {
                return ResourceManager.GetString("ErroInesperadoAtualizar", resourceCulture);
            }
        }

        public static string HistoricoProdutoAtualizado {
            get {
                return ResourceManager.GetString("HistoricoProdutoAtualizado", resourceCulture);
            }
        }

        public static string SucessoCadastro {
            get {
                return ResourceManager.GetString("SucessoCadastro", resourceCulture);
            }
        }

        public static string ErroCodigoBaseObrigatorio {
            get { return ResourceManager.GetString("ErroCodigoBaseObrigatorio", resourceCulture); }
        }

        public static string ErroQuantidadeLote {
            get { return ResourceManager.GetString("ErroQuantidadeLote", resourceCulture); }
        }

        public static string ErroCodigoGeradoMuitoLongo {
            get { return ResourceManager.GetString("ErroCodigoGeradoMuitoLongo", resourceCulture); }
        }

        public static string ErroCodigosGeradosExistentes {
            get { return ResourceManager.GetString("ErroCodigosGeradosExistentes", resourceCulture); }
        }

        public static string ErroInesperadoGerarLote {
            get { return ResourceManager.GetString("ErroInesperadoGerarLote", resourceCulture); }
        }

        public static string ErroSolicitanteNaoIdentificado {
            get { return ResourceManager.GetString("ErroSolicitanteNaoIdentificado", resourceCulture); }
        }

        public static string ErroInesperadoSolicitarLote {
            get { return ResourceManager.GetString("ErroInesperadoSolicitarLote", resourceCulture); }
        }

        public static string ErroProcessamentoProdutosLote {
            get { return ResourceManager.GetString("ErroProcessamentoProdutosLote", resourceCulture); }
        }

        public static string ErroProcessamentoProdutoNaoEncontrado {
            get { return ResourceManager.GetString("ErroProcessamentoProdutoNaoEncontrado", resourceCulture); }
        }
    }
}
