<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <NoWarn>1591</NoWarn>
	  <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Framework\Shared\Shared.csproj" />
    <ProjectReference Include="..\Domain\AtronStock.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\Framework\AtronNotificacoes\AtronNotificacoes.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO\Response\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\CategoriaResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CategoriaResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ClienteResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ClienteResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\FornecedorResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FornecedorResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ProdutoResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProdutoResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\EstoqueNotificacaoResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EstoqueNotificacaoResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\CategoriaResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CategoriaResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ClienteResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ClienteResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\FornecedorResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>FornecedorResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ProdutoResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ProdutoResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\EstoqueNotificacaoResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EstoqueNotificacaoResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
