// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atron.Infrastructure.Migrations
{
    [DbContext(typeof(AtronDbContext))]
    [Migration("20250419003625_Incluindo_CargaDeDados")]
    partial class Incluindo_CargaDeDados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Atron.Domain.Componentes.PropriedadeDeFluxoModulo", b =>
                {
                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("ModuloCodigo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PropriedadeDeFluxoId")
                        .HasColumnType("int");

                    b.Property<string>("PropriedadeDeFluxoCodigo")
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ModuloId", "ModuloCodigo", "PropriedadeDeFluxoId", "PropriedadeDeFluxoCodigo");

                    b.HasIndex("PropriedadeDeFluxoId", "PropriedadeDeFluxoCodigo");

                    b.ToTable("PropriedadeDeFluxoModulo");
                });

            modelBuilder.Entity("Atron.Domain.Componentes.PropriedadesDeFluxo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id", "Codigo");

                    b.ToTable("PropriedadesDeFluxo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "GRAVAR"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "CONSULTAR"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "DELETAR"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "ATUALIZAR"
                        });
                });

            modelBuilder.Entity("Atron.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DepartamentoCodigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id", "Codigo");

                    b.HasIndex("DepartamentoId", "DepartamentoCodigo");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id", "Codigo");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id", "Codigo");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "DPT",
                            Descricao = "Departamentos"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "CRG",
                            Descricao = "Cargos"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "USR",
                            Descricao = "Usuários"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "TAR",
                            Descricao = "Tarefas"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "SAL",
                            Descricao = "Salários"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "PAC",
                            Descricao = "Políticas e Acessos"
                        });
                });

            modelBuilder.Entity("Atron.Domain.Entities.PerfilDeAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCodigo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id", "Codigo");

                    b.HasIndex("UsuarioId", "UsuarioCodigo");

                    b.ToTable("PerfisDeAcesso");
                });

            modelBuilder.Entity("Atron.Domain.Entities.PerfilDeAcessoModulo", b =>
                {
                    b.Property<int>("PerfilDeAcessoId")
                        .HasColumnType("int");

                    b.Property<string>("PerfilDeAcessoCodigo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("ModuloCodigo")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PerfilDeAcessoId", "PerfilDeAcessoCodigo", "ModuloId", "ModuloCodigo");

                    b.HasIndex("ModuloId", "ModuloCodigo");

                    b.ToTable("PerfilDeAcessoModulos");
                });

            modelBuilder.Entity("Atron.Domain.Entities.PerfilDeAcessoUsuario", b =>
                {
                    b.Property<int>("PerfilDeAcessoId")
                        .HasColumnType("int");

                    b.Property<string>("PerfilDeAcessoCodigo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCodigo")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PerfilDeAcessoId", "PerfilDeAcessoCodigo", "UsuarioId", "UsuarioCodigo");

                    b.HasIndex("UsuarioId", "UsuarioCodigo");

                    b.ToTable("PerfilDeAcessoUsuarios");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Salario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ano")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("MesId")
                        .HasMaxLength(12)
                        .HasColumnType("int");

                    b.Property<int>("SalarioMensal")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "UsuarioCodigo")
                        .IsUnique();

                    b.ToTable("Salarios");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Conteudo")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<DateTime>("DataFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicial")
                        .HasColumnType("datetime2");

                    b.Property<int>("TarefaEstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCodigo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "UsuarioCodigo");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("SalarioAtual")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id", "Codigo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Atron.Domain.Entities.UsuarioCargoDepartamento", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCodigo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<string>("CargoCodigo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("DepartamentoCodigo")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UsuarioId", "UsuarioCodigo", "CargoId", "CargoCodigo", "DepartamentoId", "DepartamentoCodigo");

                    b.HasIndex("CargoId", "CargoCodigo");

                    b.HasIndex("DepartamentoId", "DepartamentoCodigo");

                    b.ToTable("UsuarioCargoDepartamento", (string)null);
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AppRole", (string)null);
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AppRoleClaim", (string)null);
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserClaim", (string)null);
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserLogin", (string)null);
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AppUserRole", (string)null);
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AppUserToken", (string)null);
                });

            modelBuilder.Entity("Atron.Domain.Componentes.PropriedadeDeFluxoModulo", b =>
                {
                    b.HasOne("Atron.Domain.Entities.Modulo", "Modulo")
                        .WithMany("PropriedadeDeFluxoModulos")
                        .HasForeignKey("ModuloId", "ModuloCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atron.Domain.Componentes.PropriedadesDeFluxo", "PropriedadesDeFluxo")
                        .WithMany("PropriedadesDeFluxoModulo")
                        .HasForeignKey("PropriedadeDeFluxoId", "PropriedadeDeFluxoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("PropriedadesDeFluxo");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Cargo", b =>
                {
                    b.HasOne("Atron.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Cargos")
                        .HasForeignKey("DepartamentoId", "DepartamentoCodigo");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Atron.Domain.Entities.PerfilDeAcesso", b =>
                {
                    b.HasOne("Atron.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId", "UsuarioCodigo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Atron.Domain.Entities.PerfilDeAcessoModulo", b =>
                {
                    b.HasOne("Atron.Domain.Entities.Modulo", "Modulo")
                        .WithMany("PerfilDeAcessoModulos")
                        .HasForeignKey("ModuloId", "ModuloCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atron.Domain.Entities.PerfilDeAcesso", "PerfilDeAcesso")
                        .WithMany("PerfilDeAcessoModulos")
                        .HasForeignKey("PerfilDeAcessoId", "PerfilDeAcessoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("PerfilDeAcesso");
                });

            modelBuilder.Entity("Atron.Domain.Entities.PerfilDeAcessoUsuario", b =>
                {
                    b.HasOne("Atron.Domain.Entities.PerfilDeAcesso", "PerfilDeAcesso")
                        .WithMany("PerfisDeAcessoUsuario")
                        .HasForeignKey("PerfilDeAcessoId", "PerfilDeAcessoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atron.Domain.Entities.Usuario", "Usuario")
                        .WithMany("PerfisDeAcessoUsuario")
                        .HasForeignKey("UsuarioId", "UsuarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilDeAcesso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Salario", b =>
                {
                    b.HasOne("Atron.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Salario")
                        .HasForeignKey("Atron.Domain.Entities.Salario", "UsuarioId", "UsuarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("Atron.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioId", "UsuarioCodigo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Atron.Domain.Entities.UsuarioCargoDepartamento", b =>
                {
                    b.HasOne("Atron.Domain.Entities.Cargo", "Cargo")
                        .WithMany("UsuarioCargoDepartamentos")
                        .HasForeignKey("CargoId", "CargoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atron.Domain.Entities.Departamento", "Departamento")
                        .WithMany("UsuarioCargoDepartamentos")
                        .HasForeignKey("DepartamentoId", "DepartamentoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atron.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioCargoDepartamentos")
                        .HasForeignKey("UsuarioId", "UsuarioCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Departamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationRoleClaim", b =>
                {
                    b.HasOne("Shared.Models.ApplicationModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationUserClaim", b =>
                {
                    b.HasOne("Shared.Models.ApplicationModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationUserLogin", b =>
                {
                    b.HasOne("Shared.Models.ApplicationModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationUserRole", b =>
                {
                    b.HasOne("Shared.Models.ApplicationModels.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.ApplicationModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.ApplicationModels.ApplicationUserToken", b =>
                {
                    b.HasOne("Shared.Models.ApplicationModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atron.Domain.Componentes.PropriedadesDeFluxo", b =>
                {
                    b.Navigation("PropriedadesDeFluxoModulo");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("UsuarioCargoDepartamentos");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("UsuarioCargoDepartamentos");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("PerfilDeAcessoModulos");

                    b.Navigation("PropriedadeDeFluxoModulos");
                });

            modelBuilder.Entity("Atron.Domain.Entities.PerfilDeAcesso", b =>
                {
                    b.Navigation("PerfilDeAcessoModulos");

                    b.Navigation("PerfisDeAcessoUsuario");
                });

            modelBuilder.Entity("Atron.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("PerfisDeAcessoUsuario");

                    b.Navigation("Salario");

                    b.Navigation("Tarefas");

                    b.Navigation("UsuarioCargoDepartamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
