//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PerfilDeAcessoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PerfilDeAcessoResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.PerfilDeAcessoResource", typeof(PerfilDeAcessoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil de acesso.
        /// </summary>
        public static string Descricao_PerfilDeAcesso {
            get {
                return ResourceManager.GetString("Descricao_PerfilDeAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        public static string Descricao_Usuario {
            get {
                return ResourceManager.GetString("Descricao_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar o perfil de acesso..
        /// </summary>
        public static string Erro_AtualizarPerfil {
            get {
                return ResourceManager.GetString("Erro_AtualizarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código informado é muito longo..
        /// </summary>
        public static string Erro_CodigoLongo {
            get {
                return ResourceManager.GetString("Erro_CodigoLongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código informado é muito pequeno..
        /// </summary>
        public static string Erro_CodigoPequeno {
            get {
                return ResourceManager.GetString("Erro_CodigoPequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível criar o perfil de acesso..
        /// </summary>
        public static string Erro_CriarPerfil {
            get {
                return ResourceManager.GetString("Erro_CriarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código ou a descrição não estão preenchidos..
        /// </summary>
        public static string Erro_DadosObrigatorios {
            get {
                return ResourceManager.GetString("Erro_DadosObrigatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descricao é muito longa..
        /// </summary>
        public static string Erro_DescricaoLonga {
            get {
                return ResourceManager.GetString("Erro_DescricaoLonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descricao é muito pequena..
        /// </summary>
        public static string Erro_DescricaoPequena {
            get {
                return ResourceManager.GetString("Erro_DescricaoPequena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O perfil de acesso está inválido para gravação..
        /// </summary>
        public static string Erro_PerfilInvalido {
            get {
                return ResourceManager.GetString("Erro_PerfilInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil de acesso não encontrado..
        /// </summary>
        public static string Erro_PerfilNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_PerfilNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro Perfil de acesso não encontrado..
        /// </summary>
        public static string Erro_RegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_RegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O relacionamento de perfil de acesso está inválido para gravação..
        /// </summary>
        public static string Erro_RelacionamentoInvalido {
            get {
                return ResourceManager.GetString("Erro_RelacionamentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível relacionar o perfil de acesso aos usuários..
        /// </summary>
        public static string Erro_RelacionarUsuarios {
            get {
                return ResourceManager.GetString("Erro_RelacionarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível remover o perfil de acesso..
        /// </summary>
        public static string Erro_RemoverPerfil {
            get {
                return ResourceManager.GetString("Erro_RemoverPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não contém nenhum módulo para relacionar ao perfil criado..
        /// </summary>
        public static string Erro_SemModulos {
            get {
                return ResourceManager.GetString("Erro_SemModulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não contém nenhum usuário para relacionar ao perfil criado..
        /// </summary>
        public static string Erro_SemUsuarios {
            get {
                return ResourceManager.GetString("Erro_SemUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil de acesso {0} atualizado com sucesso..
        /// </summary>
        public static string Mensagem_PerfilAtualizado {
            get {
                return ResourceManager.GetString("Mensagem_PerfilAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil de acesso {0} criado com sucesso..
        /// </summary>
        public static string Mensagem_PerfilCriado {
            get {
                return ResourceManager.GetString("Mensagem_PerfilCriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil removido com sucesso.
        /// </summary>
        public static string Mensagem_PerfilRemovido {
            get {
                return ResourceManager.GetString("Mensagem_PerfilRemovido", resourceCulture);
            }
        }
    }
}
