//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanejamentoCustoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanejamentoCustoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.PlanejamentoCustoResource", typeof(PlanejamentoCustoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma dos mínimos dos cargos detalhados diverge do mínimo do departamento..
        /// </summary>
        public static string Aviso_SomaMinimosDivergente {
            get {
                return ResourceManager.GetString("Aviso_SomaMinimosDivergente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ano do planejamento de custo não pode ser alterado..
        /// </summary>
        public static string Erro_AnoNaoPodeSerAlterado {
            get {
                return ResourceManager.GetString("Erro_AnoNaoPodeSerAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido criar ou alterar planejamento de custo para ano passado..
        /// </summary>
        public static string Erro_AnoPassadoNaoPermitido {
            get {
                return ResourceManager.GetString("Erro_AnoPassadoNaoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planejamento de custo de ano passado não pode ser editado..
        /// </summary>
        public static string Erro_AnoPassadoNaoPodeSerEditado {
            get {
                return ResourceManager.GetString("Erro_AnoPassadoNaoPodeSerEditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planejamento de custo de ano passado não pode ser excluído..
        /// </summary>
        public static string Erro_AnoPassadoNaoPodeSerExcluido {
            get {
                return ResourceManager.GetString("Erro_AnoPassadoNaoPodeSerExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao foi possivel atualizar o planejamento de custo {0}..
        /// </summary>
        public static string Erro_AtualizarPlanejamento {
            get {
                return ResourceManager.GetString("Erro_AtualizarPlanejamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cargo {0} possui planejamento de custo atual ou futuro e não pode ser movido para outro departamento..
        /// </summary>
        public static string Erro_CargoComPlanejamentoMovimentacao {
            get {
                return ResourceManager.GetString("Erro_CargoComPlanejamentoMovimentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cargo {0} possui planejamento de custo atual ou futuro e não pode ser removido..
        /// </summary>
        public static string Erro_CargoComPlanejamentoRemocao {
            get {
                return ResourceManager.GetString("Erro_CargoComPlanejamentoRemocao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem cargos que não pertencem ao departamento do planejamento: {0}..
        /// </summary>
        public static string Erro_CargosDeOutroDepartamento {
            get {
                return ResourceManager.GetString("Erro_CargosDeOutroDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem cargos duplicados no planejamento: {0}..
        /// </summary>
        public static string Erro_CargosDuplicados {
            get {
                return ResourceManager.GetString("Erro_CargosDuplicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem cargos pendentes de decisão no planejamento: {0}..
        /// </summary>
        public static string Erro_CargosPendentes {
            get {
                return ResourceManager.GetString("Erro_CargosPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os detalhes de cargo devem informar o código do cargo..
        /// </summary>
        public static string Erro_CodigoCargoObrigatorio {
            get {
                return ResourceManager.GetString("Erro_CodigoCargoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe planejamento de custo com este código..
        /// </summary>
        public static string Erro_CodigoExistente {
            get {
                return ResourceManager.GetString("Erro_CodigoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código do planejamento de custo não pode ser alterado..
        /// </summary>
        public static string Erro_CodigoNaoPodeSerAlterado {
            get {
                return ResourceManager.GetString("Erro_CodigoNaoPodeSerAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código do planejamento de custo é obrigatório..
        /// </summary>
        public static string Erro_CodigoObrigatorio {
            get {
                return ResourceManager.GetString("Erro_CodigoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código do planejamento de custo deve ter no máximo 10 caracteres..
        /// </summary>
        public static string Erro_CodigoTamanhoMaximo {
            get {
                return ResourceManager.GetString("Erro_CodigoTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao foi possivel criar o planejamento de custo..
        /// </summary>
        public static string Erro_CriarPlanejamento {
            get {
                return ResourceManager.GetString("Erro_CriarPlanejamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe planejamento de custo para este departamento e ano..
        /// </summary>
        public static string Erro_DepartamentoAnoExistente {
            get {
                return ResourceManager.GetString("Erro_DepartamentoAnoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O departamento {0} possui planejamento de custo atual ou futuro e não pode ser removido..
        /// </summary>
        public static string Erro_DepartamentoComPlanejamento {
            get {
                return ResourceManager.GetString("Erro_DepartamentoComPlanejamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento do planejamento de custo não encontrado..
        /// </summary>
        public static string Erro_DepartamentoNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_DepartamentoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O departamento do planejamento de custo não pode ser alterado..
        /// </summary>
        public static string Erro_DepartamentoNaoPodeSerAlterado {
            get {
                return ResourceManager.GetString("Erro_DepartamentoNaoPodeSerAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O departamento do planejamento de custo é obrigatório..
        /// </summary>
        public static string Erro_DepartamentoObrigatorio {
            get {
                return ResourceManager.GetString("Erro_DepartamentoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O departamento não possui cargos. Use planejamento apenas por departamento..
        /// </summary>
        public static string Erro_DepartamentoSemCargos {
            get {
                return ResourceManager.GetString("Erro_DepartamentoSemCargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do planejamento de custo é obrigatória..
        /// </summary>
        public static string Erro_DescricaoObrigatoria {
            get {
                return ResourceManager.GetString("Erro_DescricaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do planejamento de custo deve ter no máximo 100 caracteres..
        /// </summary>
        public static string Erro_DescricaoTamanhoMaximo {
            get {
                return ResourceManager.GetString("Erro_DescricaoTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planejamento de custo não encontrado..
        /// </summary>
        public static string Erro_PlanejamentoNaoEncontrado {
            get {
                return ResourceManager.GetString("Erro_PlanejamentoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao foi possivel remover o planejamento de custo {0}..
        /// </summary>
        public static string Erro_RemoverPlanejamento {
            get {
                return ResourceManager.GetString("Erro_RemoverPlanejamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma dos tetos dos cargos não pode ultrapassar o teto do departamento..
        /// </summary>
        public static string Erro_SomaTetosUltrapassaDepartamento {
            get {
                return ResourceManager.GetString("Erro_SomaTetosUltrapassaDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os cargos foram marcados como não detalhados. Use planejamento apenas por departamento..
        /// </summary>
        public static string Erro_TodosCargosNaoDetalhados {
            get {
                return ResourceManager.GetString("Erro_TodosCargosNaoDetalhados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe valor mínimo e teto para o cargo {0}..
        /// </summary>
        public static string Erro_ValoresCargoObrigatorios {
            get {
                return ResourceManager.GetString("Erro_ValoresCargoObrigatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor mínimo do cargo {0} deve ser menor que o teto..
        /// </summary>
        public static string Erro_ValorMinimoCargoMaiorTeto {
            get {
                return ResourceManager.GetString("Erro_ValorMinimoCargoMaiorTeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor mínimo do cargo {0} não pode ser negativo..
        /// </summary>
        public static string Erro_ValorMinimoCargoNegativo {
            get {
                return ResourceManager.GetString("Erro_ValorMinimoCargoNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor mínimo deve ser menor que o valor teto do planejamento de custo..
        /// </summary>
        public static string Erro_ValorMinimoMaiorTeto {
            get {
                return ResourceManager.GetString("Erro_ValorMinimoMaiorTeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor mínimo do planejamento de custo não pode ser negativo..
        /// </summary>
        public static string Erro_ValorMinimoNegativo {
            get {
                return ResourceManager.GetString("Erro_ValorMinimoNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor teto do cargo {0} deve ser maior que zero..
        /// </summary>
        public static string Erro_ValorTetoCargoInvalido {
            get {
                return ResourceManager.GetString("Erro_ValorTetoCargoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor teto do planejamento de custo deve ser maior que zero..
        /// </summary>
        public static string Erro_ValorTetoInvalido {
            get {
                return ResourceManager.GetString("Erro_ValorTetoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planejamento de custo {0} atualizado com sucesso..
        /// </summary>
        public static string Mensagem_PlanejamentoAtualizado {
            get {
                return ResourceManager.GetString("Mensagem_PlanejamentoAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planejamento de custo {0} criado com sucesso..
        /// </summary>
        public static string Mensagem_PlanejamentoCriado {
            get {
                return ResourceManager.GetString("Mensagem_PlanejamentoCriado", resourceCulture);
            }
        }
    }
}
